#pragma once
// Generated from localization/names-ko.json.
struct KoreanName { const char *en; const char *ko; };
static const KoreanName KOREAN_NAMES[] = {
  { "AARON", "충호" },
  { "ABOMASNOW", "눈설왕" },
  { "ABRA", "캐이시" },
  { "ABSOL", "앱솔" },
  { "ABSORB", "흡수" },
  { "ACCELEROCK", "액셀록" },
  { "ACCELGOR", "어지리더" },
  { "ACE F", "엘리트 여" },
  { "ACE M", "엘리트 남" },
  { "ACEROLA", "아세로라" },
  { "ACID", "용해액" },
  { "ACID ARMOR", "녹기" },
  { "ACID SPRAY", "애시드봄" },
  { "ACROBATICS", "애크러뱃" },
  { "ACUPRESSURE", "경혈찌르기" },
  { "AEGISLASH", "킬가르도" },
  { "AERIAL ACE", "제비반환" },
  { "AEROBLAST", "에어로블라스트" },
  { "AERODACTYL", "프테라" },
  { "AFTER YOU", "당신먼저" },
  { "AGATHA", "국화" },
  { "AGGRON", "보스로라" },
  { "AGILITY", "고속이동" },
  { "AIPOM", "에이팜" },
  { "AIR CUTTER", "에어커터" },
  { "AIR SLASH", "에어슬래시" },
  { "AKALA", "아칼라섬" },
  { "ALAKAZAM", "후딘" },
  { "ALCREMIE", "마휘핑" },
  { "ALL", "전체" },
  { "ALLY SWITCH", "사이드체인지" },
  { "ALOLA", "알로라" },
  { "ALOMOMOLA", "맘복치" },
  { "ALTARIA", "파비코리" },
  { "AMAURA", "아마루스" },
  { "AMBIPOM", "겟핸보숭" },
  { "AMNESIA", "망각술" },
  { "AMOONGUSS", "뽀록나" },
  { "AMPHAROS", "전룡" },
  { "ANCHOR SHOT", "앵커샷" },
  { "ANCIENTPOWER", "원시의힘" },
  { "ANISTAR", "향전시티" },
  { "ANNIHILAPE", "저승갓숭" },
  { "ANORITH", "아노딥스" },
  { "APPLE ACID", "사과산" },
  { "APPLETUN", "단지래플" },
  { "APPLIN", "과사삭벌레" },
  { "AQUA CUTTER", "아쿠아커터" },
  { "AQUA JET", "아쿠아제트" },
  { "AQUA RING", "아쿠아링" },
  { "AQUA STEP", "아쿠아스텝" },
  { "AQUA TAIL", "아쿠아테일" },
  { "ARAQUANID", "깨비물거미" },
  { "ARBOK", "아보크" },
  { "ARBOLIVA", "올리르바" },
  { "ARCANINE", "윈디" },
  { "ARCEUS", "아르세우스" },
  { "ARCHALUDON", "브리두라스" },
  { "ARCHEN", "아켄" },
  { "ARCHEOPS", "아케오스" },
  { "ARCTIBAX", "드니꽁" },
  { "ARCTOVISH", "어치르돈" },
  { "ARCTOZOLT", "파치르돈" },
  { "ARIADOS", "아리아도스" },
  { "ARM THRUST", "손바닥치기" },
  { "ARMALDO", "아말도" },
  { "ARMAROUGE", "카디나르마" },
  { "ARMOR CANNON", "아머캐논" },
  { "AROMATHERAPY", "아로마테라피" },
  { "AROMATIC MIST", "아로마미스트" },
  { "AROMATISSE", "프레프티르" },
  { "ARON", "가보리" },
  { "ARROKUDA", "찌로꼬치" },
  { "ARTICUNO", "프리져" },
  { "ASPERTIA", "부채시티" },
  { "ASSURANCE", "승부굳히기" },
  { "ASTONISH", "놀래키기" },
  { "ATTACK ORDER", "공격지령" },
  { "ATTRACT", "헤롱헤롱" },
  { "AUDINO", "다부니" },
  { "AURA SPHERE", "파동탄" },
  { "AURA WHEEL", "오라휠" },
  { "AURORA BEAM", "오로라빔" },
  { "AURORA VEIL", "오로라베일" },
  { "AURORUS", "아마루르가" },
  { "AUTOTOMIZE", "바디퍼지" },
  { "AVALANCHE", "눈사태" },
  { "AVALUGG", "크레베이스" },
  { "AXE KICK", "발꿈치찍기" },
  { "AXEW", "터검니" },
  { "AZALEA", "고동마을" },
  { "AZELF", "아그놈" },
  { "AZUMARILL", "마릴리" },
  { "AZURILL", "루리리" },
  { "BABY-DOLL EYES", "초롱초롱눈동자" },
  { "BAGON", "아공이" },
  { "BALTOY", "오뚝군" },
  { "BANEFUL BUNKER", "토치카" },
  { "BANETTE", "다크펫" },
  { "BARB BARRAGE", "독침천발" },
  { "BARBARACLE", "거북손데스" },
  { "BARBOACH", "미꾸리" },
  { "BARRASKEWDA", "꼬치조" },
  { "BARRIER", "배리어" },
  { "BASCULEGION", "대쓰여너" },
  { "BASCULIN", "배쓰나이" },
  { "BASTIODON", "바리톱스" },
  { "BATON PASS", "배턴터치" },
  { "BAXCALIBUR", "드닐레이브" },
  { "BAYLEEF", "베이리프" },
  { "BEAK BLAST", "부리캐논" },
  { "BEARTIC", "툰베어" },
  { "BEAT UP", "집단구타" },
  { "BEAUTIFLY", "뷰티플라이" },
  { "BEEDRILL", "독침붕" },
  { "BEHEEYEM", "벰크" },
  { "BELCH", "트림" },
  { "BELDUM", "메탕" },
  { "BELLIBOLT", "찌리배리" },
  { "BELLOSSOM", "아르코" },
  { "BELLSPROUT", "모다피" },
  { "BELLY DRUM", "배북" },
  { "BERGMITE", "꽁어름" },
  { "BERTHA", "들국화" },
  { "BEWEAR", "이븐곰" },
  { "BIBAREL", "비버통" },
  { "BIDE", "참기" },
  { "BIDOOF", "비버니" },
  { "BINACLE", "거북손손" },
  { "BIND", "조이기" },
  { "BISHARP", "절각참" },
  { "BITE", "물기" },
  { "BITTER BLADE", "원념의칼" },
  { "BLACEPHALON", "두파팡" },
  { "BLACKTHORN", "검은먹시티" },
  { "BLAINE", "강연" },
  { "BLASTOISE", "거북왕" },
  { "BLAZE KICK", "블레이즈킥" },
  { "BLAZIKEN", "번치코" },
  { "BLEAKWIND STORM", "찬바람폭풍" },
  { "BLIPBUG", "두루지벌레" },
  { "BLISSEY", "해피너스" },
  { "BLITZLE", "줄뮤마" },
  { "BLIZZARD", "눈보라" },
  { "BLOCK", "블록" },
  { "BLUE", "그린" },
  { "BLUE FLARE", "푸른불꽃" },
  { "BODY PRESS", "바디프레스" },
  { "BODY SLAM", "누르기" },
  { "BOLDORE", "암트르" },
  { "BOLT BEAK", "전격부리" },
  { "BOLT STRIKE", "뇌격" },
  { "BOLTUND", "펄스멍" },
  { "BOMBIRDIER", "떨구새" },
  { "BONE CLUB", "뼈다귀치기" },
  { "BONE RUSH", "본러시" },
  { "BONEMERANG", "뼈다귀부메랑" },
  { "BONSLY", "꼬지지" },
  { "BOOMBURST", "폭음파" },
  { "BOUFFALANT", "버프론" },
  { "BOUNCE", "뛰어오르기" },
  { "BOUNSWEET", "달콤아" },
  { "BRAIXEN", "테르나" },
  { "BRAMBLEGHAST", "공푸리" },
  { "BRAMBLIN", "그푸리" },
  { "BRANCH POKE", "가지찌르기" },
  { "BRAVE BIRD", "브레이브버드" },
  { "BRAVIARY", "워글" },
  { "BRAWLY", "철구" },
  { "BREAKING SWIPE", "와이드브레이커" },
  { "BRELOOM", "버섯모" },
  { "BRICK BREAK", "깨뜨리다" },
  { "BRINE", "소금물" },
  { "BRIONNE", "키요공" },
  { "BROCK", "웅" },
  { "BRONZONG", "동탁군" },
  { "BRONZOR", "동미러" },
  { "BRUNO", "시바" },
  { "BRUTAL SWING", "세차게휘두르기" },
  { "BRUTE BONNET", "사나운버섯" },
  { "BRUXISH", "치갈기" },
  { "BUBBLE", "거품" },
  { "BUBBLE BEAM", "거품광선" },
  { "BUDEW", "꼬몽울" },
  { "BUG", "벌레" },
  { "BUG BITE", "벌레먹기" },
  { "BUG BUZZ", "벌레의야단법석" },
  { "BUGSY", "호일" },
  { "BUIZEL", "브이젤" },
  { "BULBASAUR", "이상해씨" },
  { "BULK UP", "벌크업" },
  { "BULLDOZE", "땅고르기" },
  { "BULLET PUNCH", "불릿펀치" },
  { "BULLET SEED", "씨기관총" },
  { "BUNEARY", "이어롤" },
  { "BUNNELBY", "파르빗" },
  { "BURGH", "아티" },
  { "BURMY", "도롱충이" },
  { "BURN UP", "불사르기" },
  { "BURNING BULWARK", "화염의수호" },
  { "BUTTERFREE", "버터플" },
  { "BUZZWOLE", "매시붕" },
  { "BYRON", "동관" },
  { "CACNEA", "선인왕" },
  { "CACTURNE", "밤선인" },
  { "CAITLIN", "카틀레야" },
  { "CALM MIND", "명상" },
  { "CALYREX", "버드렉스" },
  { "CAMERUPT", "폭타" },
  { "CANALAVE", "운하시티" },
  { "CANDICE", "무청" },
  { "CAPSAKID", "캡싸이" },
  { "CARBINK", "멜리시" },
  { "CARKOL", "탄차곤" },
  { "CARNIVINE", "무스틈니" },
  { "CARRACOSTA", "늑골라" },
  { "CARVANHA", "샤프니아" },
  { "CASCOON", "카스쿤" },
  { "CASTELIA", "구름시티" },
  { "CASTFORM", "캐스퐁" },
  { "CATERPIE", "캐터피" },
  { "CELADON", "무지개시티" },
  { "CELEBI", "세레비" },
  { "CELESTEELA", "철화구야" },
  { "CENTISKORCH", "다태우지네" },
  { "CERULEAN", "블루시티" },
  { "CERULEDGE", "파라블레이즈" },
  { "CETITAN", "우락고래" },
  { "CETODDLE", "터벅고래" },
  { "CHAMPION", "챔피언" },
  { "CHANDELURE", "샹델라" },
  { "CHANSEY", "럭키" },
  { "CHARCADET", "카르본" },
  { "CHARGE", "충전" },
  { "CHARGE BEAM", "차지빔" },
  { "CHARIZARD", "리자몽" },
  { "CHARJABUG", "전지충이" },
  { "CHARM", "애교부리기" },
  { "CHARMANDER", "파이리" },
  { "CHARMELEON", "리자드" },
  { "CHATOT", "페라페" },
  { "CHEREN", "체렌" },
  { "CHERRIM", "체리꼬" },
  { "CHERUBI", "체리버" },
  { "CHESNAUGHT", "브리가론" },
  { "CHESPIN", "도치마론" },
  { "CHEWTLE", "깨물부기" },
  { "CHI-YU", "위유이" },
  { "CHIEN-PAO", "파오젠" },
  { "CHIKORITA", "치코리타" },
  { "CHIMCHAR", "불꽃숭이" },
  { "CHIMECHO", "치렁" },
  { "CHINCHOU", "초라기" },
  { "CHINGLING", "랑딸랑" },
  { "CHUCK", "사도" },
  { "CIANWOOD", "진청시티" },
  { "CINCCINO", "치라치노" },
  { "CINDERACE", "에이스번" },
  { "CINNABAR", "홍련섬" },
  { "CIRCLE THROW", "배대뒤치기" },
  { "CLAIR", "이향" },
  { "CLAMPERL", "진주몽" },
  { "CLANGING SCALES", "스케일노이즈" },
  { "CLANGOROUS SOUL", "소울비트" },
  { "CLAUNCHER", "완철포" },
  { "CLAWITZER", "블로스터" },
  { "CLAY", "야콘" },
  { "CLAYDOL", "점토도리" },
  { "CLEAR SMOG", "클리어스모그" },
  { "CLEFABLE", "픽시" },
  { "CLEFAIRY", "삐삐" },
  { "CLEFFA", "삐" },
  { "CLEMONT", "시트론" },
  { "CLOBBOPUS", "때때무노" },
  { "CLODSIRE", "토오" },
  { "CLOSE COMBAT", "인파이트" },
  { "CLOYSTER", "파르셀" },
  { "COALOSSAL", "석탄산" },
  { "COBALION", "코바르온" },
  { "COFAGRIGUS", "데스니칸" },
  { "COIL", "똬리틀기" },
  { "COLLISION COURSE", "엑셀브레이크" },
  { "COMBEE", "세꿀버리" },
  { "COMBUSKEN", "영치코" },
  { "COMEUPPANCE", "앙갚음" },
  { "COMFEY", "큐아링" },
  { "CONFIDE", "비밀이야기" },
  { "CONFUSE RAY", "이상한빛" },
  { "CONFUSION", "염동력" },
  { "CONKELDURR", "노보청" },
  { "CONVERSION", "텍스처" },
  { "CONVERSION 2", "텍스처2" },
  { "COPPERAJAH", "대왕끼리동" },
  { "COPYCAT", "흉내쟁이" },
  { "CORE ENFORCER", "코어퍼니셔" },
  { "CORPHISH", "가재군" },
  { "CORSOLA", "코산호" },
  { "CORVIKNIGHT", "아머까오" },
  { "CORVISQUIRE", "파크로우" },
  { "COSMIC POWER", "코스믹파워" },
  { "COSMOEM", "코스모움" },
  { "COSMOG", "코스모그" },
  { "COTTON GUARD", "코튼가드" },
  { "COTTON SPORE", "목화포자" },
  { "COTTONEE", "소미안" },
  { "COUMARINE", "비익시티" },
  { "COUNTER", "카운터" },
  { "COURT CHANGE", "코트체인지" },
  { "COVET", "탐내다" },
  { "CRABHAMMER", "집게해머" },
  { "CRABOMINABLE", "모단단게" },
  { "CRABRAWLER", "오기지게" },
  { "CRADILY", "릴리요" },
  { "CRAFTY SHIELD", "트릭가드" },
  { "CRAMORANT", "윽우지" },
  { "CRANIDOS", "두개도스" },
  { "CRAWDAUNT", "가재장군" },
  { "CRESSELIA", "크레세리아" },
  { "CROAGUNK", "삐딱구리" },
  { "CROBAT", "크로뱃" },
  { "CROCALOR", "악뜨거" },
  { "CROCONAW", "엘리게이" },
  { "CROSS CHOP", "크로스촙" },
  { "CROSS POISON", "크로스포이즌" },
  { "CRUNCH", "깨물어부수기" },
  { "CRUSH CLAW", "브레이크클로" },
  { "CRUSH GRIP", "묵사발" },
  { "CRUSTLE", "암팰리스" },
  { "CRYOGONAL", "프리지오" },
  { "CUBCHOO", "코고미" },
  { "CUBONE", "탕구리" },
  { "CUFANT", "끼리동" },
  { "CURSE", "저주" },
  { "CURSOLA", "산호르곤" },
  { "CUT", "풀베기" },
  { "CUTIEFLY", "에블리" },
  { "CYCLIZAR", "모토마" },
  { "CYLLAGE", "삼채시티" },
  { "CYNDAQUIL", "브케인" },
  { "CYNTHIA", "난천" },
  { "DACHSBUN", "바우첼" },
  { "DARK", "악" },
  { "DARK PULSE", "악의파동" },
  { "DARK VOID", "다크홀" },
  { "DARKEST LARIAT", "DD래리어트" },
  { "DARKRAI", "다크라이" },
  { "DARMANITAN", "불비달마" },
  { "DARTRIX", "빼미스로우" },
  { "DARUMAKA", "달막화" },
  { "DAZZLE GLEAM", "매지컬샤인" },
  { "DECIDUEYE", "모크나이퍼" },
  { "DECORATE", "데코레이션" },
  { "DEDENNE", "데덴네" },
  { "DEERLING", "사철록" },
  { "DEFEND ORDER", "방어지령" },
  { "DEFENSE CURL", "웅크리기" },
  { "DEFOG", "안개제거" },
  { "DEINO", "모노두" },
  { "DELCATTY", "델케티" },
  { "DELIBIRD", "딜리버드" },
  { "DELPHOX", "마폭시" },
  { "DEOXYS", "테오키스" },
  { "DESTINY BOND", "길동무" },
  { "DETECT", "판별" },
  { "DEWFORD", "무로마을" },
  { "DEWGONG", "쥬레곤" },
  { "DEWOTT", "쌍검자비" },
  { "DEWPIDER", "물거미" },
  { "DHELMISE", "타타륜" },
  { "DIALGA", "디아루가" },
  { "DIAMOND STORM", "다이아스톰" },
  { "DIANCIE", "디안시" },
  { "DIANTHA", "카르네" },
  { "DIG", "구멍파기" },
  { "DIGGERSBY", "파르토" },
  { "DIGLETT", "디그다" },
  { "DIPPLIN", "과미르" },
  { "DIRE CLAW", "페이탈클로" },
  { "DISABLE", "사슬묶기" },
  { "DISARMING VOICE", "차밍보이스" },
  { "DISCHARGE", "방전" },
  { "DITTO", "메타몽" },
  { "DIVE", "다이빙" },
  { "DODRIO", "두트리오" },
  { "DODUO", "두두" },
  { "DOLLIV", "올리뇨" },
  { "DONDOZO", "어써러셔" },
  { "DONPHAN", "코리갑" },
  { "DOODLE", "배껴그리기" },
  { "DOOM DESIRE", "파멸의소원" },
  { "DOTTLER", "레돔벌레" },
  { "DOUBLADE", "쌍검킬" },
  { "DOUBLE HIT", "더블어택" },
  { "DOUBLE IRON BASH", "더블펀처" },
  { "DOUBLE KICK", "두번차기" },
  { "DOUBLE SHOCK", "전광쌍격" },
  { "DOUBLE TEAM", "그림자분신" },
  { "DOUBLE-EDGE", "이판사판태클" },
  { "DRACOVISH", "어래곤" },
  { "DRACOZOLT", "파치래곤" },
  { "DRAGALGE", "드래캄" },
  { "DRAGAPULT", "드래펄트" },
  { "DRAGON", "드래곤" },
  { "DRAGON ASCENT", "화룡점정" },
  { "DRAGON BREATH", "용의숨결" },
  { "DRAGON CLAW", "드래곤클로" },
  { "DRAGON DANCE", "용의춤" },
  { "DRAGON DARTS", "드래곤애로" },
  { "DRAGON ENERGY", "드래곤에너지" },
  { "DRAGON HAMMER", "드래곤해머" },
  { "DRAGON PULSE", "용의파동" },
  { "DRAGON RAGE", "용의분노" },
  { "DRAGON RUSH", "드래곤다이브" },
  { "DRAGON TAIL", "드래곤테일" },
  { "DRAGONAIR", "신뇽" },
  { "DRAGONITE", "망나뇽" },
  { "DRAIN KISS", "드레인키스" },
  { "DRAIN PUNCH", "드레인펀치" },
  { "DRAKE", "권수" },
  { "DRAKLOAK", "드래런치" },
  { "DRAMPA", "할비롱" },
  { "DRAPION", "드래피온" },
  { "DRASNA", "드라세나" },
  { "DRATINI", "미뇽" },
  { "DRAYDEN", "사간" },
  { "DREAM EATER", "꿈먹기" },
  { "DREDNAW", "갈가부기" },
  { "DREEPY", "드라꼰" },
  { "DRIFBLIM", "둥실라이드" },
  { "DRIFLOON", "흔들풍손" },
  { "DRIFTVEIL", "물풍경시티" },
  { "DRILBUR", "두더류" },
  { "DRILL PECK", "회전부리" },
  { "DRILL RUN", "드릴라이너" },
  { "DRIZZILE", "누겔레온" },
  { "DROWZEE", "슬리프" },
  { "DRUDDIGON", "크리만" },
  { "DRUM BEATING", "드럼어택" },
  { "DUAL WINGBEAT", "더블윙" },
  { "DUBWOOL", "배우르" },
  { "DUCKLETT", "꼬지보리" },
  { "DUDUNSPARCE", "노고고치" },
  { "DUGTRIO", "닥트리오" },
  { "DUNSPARCE", "노고치" },
  { "DUOSION", "듀란" },
  { "DURALUDON", "두랄루돈" },
  { "DURANT", "아이앤트" },
  { "DUSCLOPS", "미라몽" },
  { "DUSKNOIR", "야느와르몽" },
  { "DUSKULL", "해골몽" },
  { "DUSTOX", "독케일" },
  { "DWEBBLE", "돌살이" },
  { "DYNAMAX CANNON", "다이맥스포" },
  { "DYNAMIC PUNCH", "폭발펀치" },
  { "EARTH POWER", "대지의힘" },
  { "EARTHQUAKE", "지진" },
  { "ECHOED VOICE", "에코보이스" },
  { "ECRUTEAK", "인주시티" },
  { "EELEKTRIK", "저리릴" },
  { "EELEKTROSS", "저리더프" },
  { "EERIE IMPULSE", "괴전파" },
  { "EEVEE", "이브이" },
  { "EISCUE", "빙큐보" },
  { "EKANS", "아보" },
  { "ELDEGOSS", "백솜모카" },
  { "ELECTABUZZ", "에레브" },
  { "ELECTIVIRE", "에레키블" },
  { "ELECTRIC", "전기" },
  { "ELECTRIC TERRAIN", "일렉트릭필드" },
  { "ELECTRIFY", "송전" },
  { "ELECTRIKE", "썬더라이" },
  { "ELECTRO BALL", "일렉트릭볼" },
  { "ELECTRO DRIFT", "라이트닝드라이브" },
  { "ELECTRO SHOT", "일렉트로빔" },
  { "ELECTRODE", "붐볼" },
  { "ELECTROWEB", "일렉트릭네트" },
  { "ELEKID", "에레키드" },
  { "ELESA", "카밀레" },
  { "ELGYEM", "리그레" },
  { "ELITE 4", "사천왕" },
  { "EMBER", "불꽃세례" },
  { "EMBOAR", "염무왕" },
  { "EMOLGA", "에몽가" },
  { "EMPOLEON", "엠페르트" },
  { "ENAMORUS", "러브로스" },
  { "ENCORE", "앙코르" },
  { "ENDEAVOR", "죽기살기" },
  { "ENDURE", "버티기" },
  { "ENERGY BALL", "에너지볼" },
  { "ENTEI", "앤테이" },
  { "ENTRAINMENT", "동료만들기" },
  { "ERIKA", "민화" },
  { "ERUPTION", "분화" },
  { "ESCAVALIER", "슈바르고" },
  { "ESPATHRA", "클레스퍼트라" },
  { "ESPEON", "에브이" },
  { "ESPURR", "냐스퍼" },
  { "ETERNA", "영원시티" },
  { "ETERNATUS", "무한다이노" },
  { "EXCADRILL", "몰드류" },
  { "EXEGGCUTE", "아라리" },
  { "EXEGGUTOR", "나시" },
  { "EXPANDING FORCE", "와이드포스" },
  { "EXPLOSION", "대폭발" },
  { "EXPLOUD", "폭음룡" },
  { "EXTRASENSORY", "신통력" },
  { "EXTREME SPEED", "신속" },
  { "FACADE", "객기" },
  { "FAIRY", "페어리" },
  { "FAIRY LOCK", "페어리록" },
  { "FAIRY WIND", "요정의바람" },
  { "FAKE OUT", "속이기" },
  { "FAKE TEARS", "거짓울음" },
  { "FALINKS", "대여르" },
  { "FALKNER", "비상" },
  { "FALSE SURRENDER", "사죄의찌르기" },
  { "FALSE SWIPE", "칼등치기" },
  { "FANTINA", "멜리사" },
  { "FARFETCHD", "파오리" },
  { "FARIGIRAF", "키키링" },
  { "FEAROW", "깨비드릴조" },
  { "FEATHER DANCE", "깃털댄스" },
  { "FEEBAS", "빈티나" },
  { "FEINT", "페인트" },
  { "FELL STINGER", "마지막일침" },
  { "FENNEKIN", "푸호꼬" },
  { "FERALIGATR", "장크로다일" },
  { "FERROSEED", "철시드" },
  { "FERROTHORN", "너트령" },
  { "FEZANDIPITI", "기로치" },
  { "FICKLE BEAM", "변덕레이저" },
  { "FIDOUGH", "쫀도기" },
  { "FIERY DANCE", "불꽃춤" },
  { "FIGHTING", "격투" },
  { "FILLET AWAY", "제살깎기" },
  { "FINAL GAMBIT", "목숨걸기" },
  { "FINIZEN", "맨돌핀" },
  { "FINNEON", "형광어" },
  { "FIRE", "불꽃" },
  { "FIRE BLAST", "불대문자" },
  { "FIRE FANG", "불꽃엄니" },
  { "FIRE LASH", "불꽃채찍" },
  { "FIRE PUNCH", "불꽃펀치" },
  { "FIRE SPIN", "회오리불꽃" },
  { "FIRST IMPRESSION", "만나자마자" },
  { "FISHIOUS REND", "아가미물기" },
  { "FISSURE", "땅가르기" },
  { "FLAAFFY", "보송송" },
  { "FLABEBE", "플라베베" },
  { "FLAIL", "바둥바둥" },
  { "FLAME BURST", "불꽃튀기기" },
  { "FLAME CHARGE", "니트로차지" },
  { "FLAME WHEEL", "화염바퀴" },
  { "FLAMETHROWER", "화염방사" },
  { "FLAMIGO", "꼬이밍고" },
  { "FLANNERY", "민지" },
  { "FLAPPLE", "애프룡" },
  { "FLARE BLITZ", "플레어드라이브" },
  { "FLAREON", "부스터" },
  { "FLASH CANNON", "러스터캐논" },
  { "FLATTER", "부추기기" },
  { "FLETCHINDER", "불화살빈" },
  { "FLETCHLING", "화살꼬빈" },
  { "FLEUR CANNON", "플뢰르캐논" },
  { "FLING", "내던지기" },
  { "FLINT", "대엽" },
  { "FLIP TURN", "퀵턴" },
  { "FLITTLE", "하느라기" },
  { "FLOATZEL", "플로젤" },
  { "FLOETTE", "플라엣테" },
  { "FLORAGATO", "나로테" },
  { "FLORAL HEALING", "플라워힐" },
  { "FLORGES", "플라제스" },
  { "FLOWER TRICK", "트릭플라워" },
  { "FLUTTER MANE", "날개치는머리" },
  { "FLY", "공중날기" },
  { "FLYGON", "플라이곤" },
  { "FLYING", "비행" },
  { "FLYING PRESS", "플라잉프레스" },
  { "FOCUS BLAST", "기합구슬" },
  { "FOCUS ENERGY", "기충전" },
  { "FOCUS PUNCH", "힘껏펀치" },
  { "FOLLOW ME", "날따름" },
  { "FOMANTIS", "짜랑랑" },
  { "FOONGUS", "깜놀버슬" },
  { "FORCE PALM", "발경" },
  { "FOREST\u2019S CURSE", "숲의저주" },
  { "FORRETRESS", "쏘콘" },
  { "FORTREE", "검방울시티" },
  { "FOUL PLAY", "속임수" },
  { "FRAXURE", "액슨도" },
  { "FREEZE-DRY", "프리즈드라이" },
  { "FRIGIBAX", "드니차" },
  { "FRILLISH", "탱그릴" },
  { "FROAKIE", "개구마르" },
  { "FROGADIER", "개굴반장" },
  { "FROSLASS", "눈여아" },
  { "FROSMOTH", "모스노우" },
  { "FROST BREATH", "얼음숨결" },
  { "FUCHSIA", "연분홍시티" },
  { "FUECOCO", "뜨아거" },
  { "FURFROU", "트리미앙" },
  { "FURRET", "다꼬리" },
  { "FURY ATTACK", "마구찌르기" },
  { "FURY CUTTER", "연속자르기" },
  { "FURY SWIPES", "마구할퀴기" },
  { "FUSION BOLT", "크로스썬더" },
  { "FUSION FLARE", "크로스플레임" },
  { "FUTURE SIGHT", "미래예지" },
  { "GABITE", "한바이트" },
  { "GALAR", "가라르" },
  { "GALLADE", "엘레이드" },
  { "GALVANTULA", "전툴라" },
  { "GARBODOR", "더스트나" },
  { "GARCHOMP", "한카리아스" },
  { "GARDENIA", "유채" },
  { "GARDEVOIR", "가디안" },
  { "GARGANACL", "콜로솔트" },
  { "GASTLY", "고오스" },
  { "GASTRO ACID", "위액" },
  { "GASTRODON", "트리토돈" },
  { "GEAR GRIND", "기어소서" },
  { "GEAR UP", "어시스트기어" },
  { "GENESECT", "게노세크트" },
  { "GENGAR", "팬텀" },
  { "GEODUDE", "꼬마돌" },
  { "GEOMANCY", "지오컨트롤" },
  { "GHOLDENGO", "타부자고" },
  { "GHOST", "고스트" },
  { "GIBLE", "딥상어동" },
  { "GIGA DRAIN", "기가드레인" },
  { "GIGA IMPACT", "기가임팩트" },
  { "GIGALITH", "기가이어스" },
  { "GIGATON HAMMER", "거대해머" },
  { "GIMMIGHOUL", "모으령" },
  { "GIOVANNI", "비주기" },
  { "GIRAFARIG", "키링키" },
  { "GIRATINA", "기라티나" },
  { "GIRL", "소녀" },
  { "GLACEON", "글레이시아" },
  { "GLACIA", "미혜" },
  { "GLACIATE", "얼어붙은세계" },
  { "GLAIVE RUSH", "대검돌격" },
  { "GLALIE", "얼음귀신" },
  { "GLAMEOW", "나옹마" },
  { "GLARE", "뱀눈초리" },
  { "GLASTRIER", "블리자포스" },
  { "GLIGAR", "글라이거" },
  { "GLIMMET", "초롱순" },
  { "GLIMMORA", "킬라플로르" },
  { "GLISCOR", "글라이온" },
  { "GLOOM", "냄새꼬" },
  { "GOGOAT", "고고트" },
  { "GOLBAT", "골뱃" },
  { "GOLDEEN", "콘치" },
  { "GOLDENROD", "금빛시티" },
  { "GOLDUCK", "골덕" },
  { "GOLEM", "딱구리" },
  { "GOLETT", "골비람" },
  { "GOLISOPOD", "갑주무사" },
  { "GOLURK", "골루그" },
  { "GOODRA", "미끄래곤" },
  { "GOOMY", "미끄메라" },
  { "GOREBYSS", "분홍장이" },
  { "GOSSIFLEUR", "꼬모카" },
  { "GOTHITA", "고디탱" },
  { "GOTHITELLE", "고디모아젤" },
  { "GOTHORITA", "고디보미" },
  { "GOUGING FIRE", "꿰뚫는화염" },
  { "GOURGEIST", "펌킨인" },
  { "GRAFAIAI", "태깅구르" },
  { "GRANBULL", "그랑블루" },
  { "GRANT", "자크로" },
  { "GRAPPLOCT", "케오퍼스" },
  { "GRASS", "풀" },
  { "GRASS KNOT", "풀묶기" },
  { "GRASSY TERRAIN", "그래스필드" },
  { "GRAV APPLE", "G의힘" },
  { "GRAVELER", "데구리" },
  { "GRAVITY", "중력" },
  { "GREAT TUSK", "위대한엄니" },
  { "GREAVARD", "망망이" },
  { "GREEDENT", "요씽리스" },
  { "GRENINJA", "개굴닌자" },
  { "GRIMER", "질퍽이" },
  { "GRIMMSNARL", "오롱털" },
  { "GRIMSLEY", "블래리" },
  { "GROOKEY", "흥나숭" },
  { "GROTLE", "수풀부기" },
  { "GROUDON", "그란돈" },
  { "GROUND", "땅" },
  { "GROVYLE", "나무돌이" },
  { "GROWL", "울음소리" },
  { "GROWLITHE", "가디" },
  { "GROWTH", "성장" },
  { "GRUBBIN", "턱지충이" },
  { "GRUDGE", "원념" },
  { "GRUMPIG", "피그킹" },
  { "GUARD SPLIT", "가드셰어" },
  { "GUARD SWAP", "가드스왑" },
  { "GUILLOTINE", "가위자르기" },
  { "GULPIN", "꼴깍몬" },
  { "GUMSHOOS", "형사구스" },
  { "GUNK SHOT", "더스트슈트" },
  { "GURDURR", "토쇠골" },
  { "GUST", "바람일으키기" },
  { "GUZZLORD", "악식킹" },
  { "GYARADOS", "갸라도스" },
  { "GYRO BALL", "자이로볼" },
  { "HAIL", "싸라기눈" },
  { "HAKAMO O", "짜랑고우" },
  { "HALA", "할라" },
  { "HAMMER ARM", "암해머" },
  { "HAPPINY", "핑복" },
  { "HAPU", "하푸우" },
  { "HARDEN", "단단해지기" },
  { "HARIYAMA", "하리뭉" },
  { "HATENNA", "몸지브림" },
  { "HATTERENE", "브리무음" },
  { "HATTREM", "손지브림" },
  { "HAUNTER", "고우스트" },
  { "HAWLUCHA", "루차불" },
  { "HAXORUS", "액스라이즈" },
  { "HAZE", "흑안개" },
  { "HEAD CHARGE", "아프로브레이크" },
  { "HEAD SMASH", "양날박치기" },
  { "HEADBUTT", "박치기" },
  { "HEADLONG RUSH", "들이받기" },
  { "HEAL BELL", "치료방울" },
  { "HEAL PULSE", "치유파동" },
  { "HEALING WISH", "치유소원" },
  { "HEART SWAP", "하트스왑" },
  { "HEARTHOME", "연고시티" },
  { "HEAT CRASH", "히트스탬프" },
  { "HEAT WAVE", "열풍" },
  { "HEATMOR", "앤티골" },
  { "HEATRAN", "히드런" },
  { "HEAVY SLAM", "헤비봄버" },
  { "HELIOLISK", "일레도리자드" },
  { "HELIOPTILE", "목도리키텔" },
  { "HELPING HAND", "도우미" },
  { "HERACROSS", "헤라크로스" },
  { "HERDIER", "하데리어" },
  { "HEX", "병상첨병" },
  { "HI JUMP KICK", "무릎차기" },
  { "HIDDEN POWER", "잠재파워" },
  { "HIGH HORSEPOWER", "10만마력" },
  { "HIKER", "등산가" },
  { "HIPPOPOTAS", "히포포타스" },
  { "HIPPOWDON", "하마돈" },
  { "HITMONCHAN", "홍수몬" },
  { "HITMONLEE", "시라소몬" },
  { "HITMONTOP", "카포에라" },
  { "HO-OH", "칠색조" },
  { "HOENN", "호연" },
  { "HONCHKROW", "돈크로우" },
  { "HONE CLAWS", "손톱갈기" },
  { "HONEDGE", "단칼빙" },
  { "HOOPA", "후파" },
  { "HOOTHOOT", "부우부" },
  { "HOPPIP", "통통코" },
  { "HORN ATTACK", "뿔찌르기" },
  { "HORN DRILL", "뿔드릴" },
  { "HORN LEECH", "우드혼" },
  { "HORSEA", "쏘드라" },
  { "HOUNDOOM", "헬가" },
  { "HOUNDOUR", "델빌" },
  { "HOUNDSTONE", "묘두기" },
  { "HOWL", "멀리짖기" },
  { "HUMILAU", "기하시티" },
  { "HUNTAIL", "헌테일" },
  { "HURRICANE", "폭풍" },
  { "HYDRAPPLE", "과미드라" },
  { "HYDREIGON", "삼삼드래" },
  { "HYDRO PUMP", "하이드로펌프" },
  { "HYDRO STEAM", "하이드로스팀" },
  { "HYPER BEAM", "파괴광선" },
  { "HYPER DRILL", "하이퍼드릴" },
  { "HYPER FANG", "필살앞니" },
  { "HYPER VOICE", "하이퍼보이스" },
  { "HYPERSPACE HOLE", "이차원홀" },
  { "HYPNO", "슬리퍼" },
  { "HYPNOSIS", "최면술" },
  { "ICE", "얼음" },
  { "ICE BEAM", "냉동빔" },
  { "ICE FANG", "얼음엄니" },
  { "ICE HAMMER", "아이스해머" },
  { "ICE PUNCH", "냉동펀치" },
  { "ICE SHARD", "얼음뭉치" },
  { "ICE SPINNER", "아이스스피너" },
  { "ICICLE CRASH", "고드름떨구기" },
  { "ICICLE SPEAR", "고드름침" },
  { "ICY WIND", "얼어붙은바람" },
  { "IGGLYBUFF", "푸푸린" },
  { "ILIMA", "일리마" },
  { "ILLUMISE", "네오비트" },
  { "IMPIDIMP", "메롱꿍" },
  { "IMPRISON", "봉인" },
  { "INCINERATE", "불태우기" },
  { "INCINEROAR", "어흥염" },
  { "INDEEDEE", "에써르" },
  { "INFERNAPE", "초염몽" },
  { "INFERNO", "연옥" },
  { "INFESTATION", "엉겨붙기" },
  { "INGRAIN", "뿌리박기" },
  { "INKAY", "오케이징" },
  { "INSTRUCT", "지휘" },
  { "INTELEON", "인텔리레온" },
  { "IRIS", "아이리스" },
  { "IRON BOULDER", "무쇠암석" },
  { "IRON BUNDLE", "무쇠보따리" },
  { "IRON CROWN", "무쇠감투" },
  { "IRON DEFENSE", "철벽" },
  { "IRON HANDS", "무쇠손" },
  { "IRON HEAD", "아이언헤드" },
  { "IRON JUGULIS", "무쇠머리" },
  { "IRON LEAVES", "무쇠잎새" },
  { "IRON MOTH", "무쇠독나방" },
  { "IRON TAIL", "아이언테일" },
  { "IRON THORNS", "무쇠가시" },
  { "IRON TREADS", "무쇠바퀴" },
  { "IRON VALIANT", "무쇠무인" },
  { "IVY CUDGEL", "덩굴방망이" },
  { "IVYSAUR", "이상해풀" },
  { "JANGMO O", "짜랑꼬" },
  { "JASMINE", "규리" },
  { "JAW LOCK", "물고버티기" },
  { "JELLICENT", "탱탱겔" },
  { "JET PUNCH", "제트펀치" },
  { "JIGGLYPUFF", "푸린" },
  { "JIRACHI", "지라치" },
  { "JOHTO", "성도" },
  { "JOLTEON", "쥬피썬더" },
  { "JOLTIK", "파쪼옥" },
  { "JUAN", "아단" },
  { "JUDGMENT", "심판의뭉치" },
  { "JUMPLUFF", "솜솜코" },
  { "JUNGLE HEALING", "정글힐" },
  { "JYNX", "루주라" },
  { "KABUTO", "투구" },
  { "KABUTOPS", "투구푸스" },
  { "KADABRA", "윤겔라" },
  { "KAHILI", "카일리" },
  { "KAKUNA", "딱충이" },
  { "KALOS", "칼로스" },
  { "KANGASKHAN", "캥카" },
  { "KANTO", "관동" },
  { "KARATE CHOP", "태권당수" },
  { "KAREN", "카렌" },
  { "KARRABLAST", "딱정곤" },
  { "KARTANA", "종이신도" },
  { "KECLEON", "켈리몬" },
  { "KELDEO", "케르디오" },
  { "KIAWE", "키아웨" },
  { "KILOWATTREL", "찌리비크" },
  { "KINGAMBIT", "대도각참" },
  { "KINGDRA", "킹드라" },
  { "KINGLER", "킹크랩" },
  { "KING\u2019S SHIELD", "킹실드" },
  { "KIRLIA", "킬리아" },
  { "KLANG", "기기어르" },
  { "KLAWF", "절벼게" },
  { "KLEAVOR", "사마자르" },
  { "KLEFKI", "클레피" },
  { "KLINK", "기어르" },
  { "KLINKLANG", "기기기어르" },
  { "KNOCK OFF", "탁쳐서떨구기" },
  { "KOFFING", "또가스" },
  { "KOGA", "독수" },
  { "KOMALA", "자말라" },
  { "KOMMO O", "짜랑고우거" },
  { "KORAIDON", "코라이돈" },
  { "KORRINA", "코르니" },
  { "KOWTOW CLEAVE", "도각참" },
  { "KRABBY", "크랩" },
  { "KRICKETOT", "귀뚤뚜기" },
  { "KRICKETUNE", "귀뚤톡크" },
  { "KROKOROK", "악비르" },
  { "KROOKODILE", "악비아르" },
  { "KUBFU", "치고마" },
  { "KUKUI", "쿠쿠이" },
  { "KYOGRE", "가이오가" },
  { "KYUREM", "큐레무" },
  { "LAIRON", "갱도라" },
  { "LAMPENT", "램프라" },
  { "LANA", "수련" },
  { "LANCE", "목호" },
  { "LANDORUS", "랜드로스" },
  { "LAND\u2019S WRATH", "그라운드포스" },
  { "LANTURN", "랜턴" },
  { "LAPRAS", "라프라스" },
  { "LARVESTA", "활화르바" },
  { "LARVITAR", "애버라스" },
  { "LASER FOCUS", "예민해지기" },
  { "LAST RESORT", "비장의무기" },
  { "LAST RESPECTS", "성묘" },
  { "LATIAS", "라티아스" },
  { "LATIOS", "라티오스" },
  { "LAVA PLUME", "분연" },
  { "LAVARIDGE", "용암마을" },
  { "LAVERRE", "후늬시티" },
  { "LEAF BLADE", "리프블레이드" },
  { "LEAF STORM", "리프스톰" },
  { "LEAF TORNADO", "그래스믹서" },
  { "LEAFAGE", "나뭇잎" },
  { "LEAFEON", "리피아" },
  { "LEAVANNY", "모아머" },
  { "LECHONK", "맛보돈" },
  { "LEDIAN", "레디안" },
  { "LEDYBA", "레디바" },
  { "LEECH LIFE", "흡혈" },
  { "LEECH SEED", "씨뿌리기" },
  { "LEER", "째려보기" },
  { "LICK", "핥기" },
  { "LICKILICKY", "내룸벨트" },
  { "LICKITUNG", "내루미" },
  { "LIEPARD", "레파르다스" },
  { "LIFE DEW", "생명의물방울" },
  { "LIGHT SCREEN", "빛의장막" },
  { "LILEEP", "릴링" },
  { "LILLIGANT", "드레디어" },
  { "LILLIPUP", "요테리" },
  { "LINOONE", "직구리" },
  { "LIQUIDATION", "아쿠아브레이크" },
  { "LITLEO", "레오꼬" },
  { "LITTEN", "냐오불" },
  { "LITWICK", "불켜미" },
  { "LOCK-ON", "록온" },
  { "LOKIX", "엑스레그" },
  { "LOMBRE", "로토스" },
  { "LOPUNNY", "이어롭" },
  { "LORELEI", "칸나" },
  { "LOTAD", "연꽃몬" },
  { "LOUDRED", "노공룡" },
  { "LOVELY KISS", "악마의키스" },
  { "LOW KICK", "안다리걸기" },
  { "LOW SWEEP", "로킥" },
  { "LT SURGE", "마티스" },
  { "LUCARIO", "루카리오" },
  { "LUCIAN", "오엽" },
  { "LUDICOLO", "로파파" },
  { "LUGIA", "루기아" },
  { "LUMINA CRASH", "루미나콜리전" },
  { "LUMINEON", "네오라이트" },
  { "LUMIOSE", "미르시티" },
  { "LUNALA", "루나아라" },
  { "LUNAR BLESSING", "초승달의기도" },
  { "LUNAR DANCE", "초승달춤" },
  { "LUNATONE", "루나톤" },
  { "LUNGE", "덤벼들기" },
  { "LURANTIS", "라란티스" },
  { "LUSTER PURGE", "러스터퍼지" },
  { "LUVDISC", "사랑동이" },
  { "LUXIO", "럭시오" },
  { "LUXRAY", "렌트라" },
  { "LYCANROC", "루가루암" },
  { "MABOSSTIFF", "마피티프" },
  { "MACH PUNCH", "마하펀치" },
  { "MACHAMP", "괴력몬" },
  { "MACHOKE", "근육몬" },
  { "MACHOP", "알통몬" },
  { "MAGBY", "마그비" },
  { "MAGCARGO", "마그카르고" },
  { "MAGEARNA", "마기아나" },
  { "MAGIC COAT", "매직코트" },
  { "MAGIC LEAF", "매지컬리프" },
  { "MAGIC POWDER", "마법가루" },
  { "MAGIC ROOM", "매직룸" },
  { "MAGIKARP", "잉어킹" },
  { "MAGMA STORM", "마그마스톰" },
  { "MAGMAR", "마그마" },
  { "MAGMORTAR", "마그마번" },
  { "MAGNEMITE", "코일" },
  { "MAGNET RISE", "전자부유" },
  { "MAGNETIC FLUX", "자기장조작" },
  { "MAGNETON", "레어코일" },
  { "MAGNEZONE", "자포코일" },
  { "MAHOGANY", "황토마을" },
  { "MAKE IT RAIN", "골드러시" },
  { "MAKUHITA", "마크탕" },
  { "MALAMAR", "칼라마네로" },
  { "MALIGN CHAIN", "악독사슬" },
  { "MALLOW", "마오" },
  { "MALVA", "파키라" },
  { "MAMOSWINE", "맘모꾸리" },
  { "MANAPHY", "마나피" },
  { "MANDIBUZZ", "버랜지나" },
  { "MANECTRIC", "썬더볼트" },
  { "MANKEY", "망키" },
  { "MANTINE", "만타인" },
  { "MANTYKE", "타만타" },
  { "MARACTUS", "마라카치" },
  { "MAREANIE", "시마사리" },
  { "MAREEP", "메리프" },
  { "MARILL", "마릴" },
  { "MARLON", "시즈" },
  { "MAROWAK", "텅구리" },
  { "MARSHADOW", "마샤도" },
  { "MARSHAL", "연무" },
  { "MARSHTOMP", "늪짱이" },
  { "MASCHIFF", "오라티프" },
  { "MASQUERAIN", "비나방" },
  { "MATCHA GOTCHA", "휘적휘적포" },
  { "MAUSHOLD", "파밀리쥐" },
  { "MAUVILLE", "보라시티" },
  { "MAWILE", "입치트" },
  { "MAYLENE", "자두" },
  { "MEAN LOOK", "검은눈빛" },
  { "MEDICHAM", "요가램" },
  { "MEDITITE", "요가랑" },
  { "MEGA DRAIN", "메가드레인" },
  { "MEGA KICK", "메가톤킥" },
  { "MEGA PUNCH", "메가톤펀치" },
  { "MEGAHORN", "메가혼" },
  { "MEGANIUM", "메가니움" },
  { "MELEMELE", "멜레멜레섬" },
  { "MELMETAL", "멜메탈" },
  { "MELOETTA", "메로엣타" },
  { "MELTAN", "멜탄" },
  { "MEMENTO", "추억의선물" },
  { "MEOWSCARADA", "마스카나" },
  { "MEOWSTIC", "냐오닉스" },
  { "MEOWTH", "나옹" },
  { "MESPRIT", "엠라이트" },
  { "METAGROSS", "메타그로스" },
  { "METAL BURST", "메탈버스트" },
  { "METAL CLAW", "메탈클로" },
  { "METAL SOUND", "금속음" },
  { "METANG", "메탕구" },
  { "METAPOD", "단데기" },
  { "METEOR ASSAULT", "스타어설트" },
  { "METEOR MASH", "코멧펀치" },
  { "METRONOME", "손가락흔들기" },
  { "MEW", "뮤" },
  { "MEWTWO", "뮤츠" },
  { "MIENFOO", "비조푸" },
  { "MIENSHAO", "비조도" },
  { "MIGHTY CLEAVE", "파워풀에지" },
  { "MIGHTYENA", "그라에나" },
  { "MILCERY", "마빌크" },
  { "MILK DRINK", "우유마시기" },
  { "MILOTIC", "밀로틱" },
  { "MILTANK", "밀탱크" },
  { "MIME JR", "흉내내" },
  { "MIMIC", "흉내내기" },
  { "MIMIKYU", "따라큐" },
  { "MINA", "말리화" },
  { "MINCCINO", "치라미" },
  { "MIND BLOWN", "깜짝헤드" },
  { "MIND READER", "마음의눈" },
  { "MINIMIZE", "작아지기" },
  { "MINIOR", "메테노" },
  { "MINUN", "마이농" },
  { "MIRAIDON", "미라이돈" },
  { "MIRROR COAT", "미러코트" },
  { "MISDREAVUS", "무우마" },
  { "MISMAGIUS", "무우마직" },
  { "MIST", "흰안개" },
  { "MIST BALL", "미스트볼" },
  { "MISTRALTON", "궐수시티" },
  { "MISTY", "이슬" },
  { "MISTY TERRAIN", "미스트필드" },
  { "MOLTRES", "파이어" },
  { "MONFERNO", "파이숭이" },
  { "MOONBLAST", "문포스" },
  { "MOONGEIST BEAM", "섀도레이" },
  { "MOONLIGHT", "달빛" },
  { "MORELULL", "자마슈" },
  { "MORGREM", "쏘겨모" },
  { "MORNING SUN", "아침햇살" },
  { "MORPEKO", "모르페코" },
  { "MORTAL SPIN", "킬러스핀" },
  { "MORTY", "유빈" },
  { "MOSSDEEP", "이끼시티" },
  { "MOTHIM", "나메일" },
  { "MR. MIME", "마임맨" },
  { "MR. RIME", "마임꽁꽁" },
  { "MUD SHOT", "머드샷" },
  { "MUD-SLAP", "진흙뿌리기" },
  { "MUDBRAY", "머드나기" },
  { "MUDDY WATER", "탁류" },
  { "MUDKIP", "물짱이" },
  { "MUDSDALE", "만마드" },
  { "MUK", "질뻐기" },
  { "MULTI-ATTACK", "멀티어택" },
  { "MUNCHLAX", "먹고자" },
  { "MUNKIDORI", "이야후" },
  { "MUNNA", "몽나" },
  { "MURKROW", "니로우" },
  { "MUSHARNA", "몽얌나" },
  { "MYSTICAL FIRE", "매지컬플레임" },
  { "MYSTICAL POWER", "신비의힘" },
  { "NACLI", "베베솔트" },
  { "NACLSTACK", "스태솔트" },
  { "NAGANADEL", "아고용" },
  { "NANU", "나누" },
  { "NASTY PLOT", "나쁜음모" },
  { "NATU", "네이티" },
  { "NATURAL GIFT", "자연의은혜" },
  { "NATURE POWER", "자연의힘" },
  { "NATURE\u2019S MADNESS", "자연의분노" },
  { "NECROZMA", "네크로즈마" },
  { "NICKIT", "훔처우" },
  { "NIDOKING", "니드킹" },
  { "NIDOQUEEN", "니드퀸" },
  { "NIDORAN H", "니드런♀" },
  { "NIDORAN M", "니드런♂" },
  { "NIDORINA", "니드리나" },
  { "NIDORINO", "니드리노" },
  { "NIGHT DAZE", "나이트버스트" },
  { "NIGHT SHADE", "나이트헤드" },
  { "NIGHT SLASH", "깜짝베기" },
  { "NIHILEGO", "텅비드" },
  { "NIMBASA", "뇌문시티" },
  { "NINCADA", "토중몬" },
  { "NINETALES", "나인테일" },
  { "NINJASK", "아이스크" },
  { "NO RETREAT", "배수의진" },
  { "NOBLE ROAR", "부르짖기" },
  { "NOCTOWL", "야부엉" },
  { "NOIBAT", "음뱃" },
  { "NOIVERN", "음번" },
  { "NORMAL", "노말" },
  { "NORMAN", "종길" },
  { "NOSEPASS", "코코파스" },
  { "NUMEL", "둔타" },
  { "NUZLEAF", "잎새코" },
  { "NUZZLE", "볼부비부비" },
  { "NYMBLE", "콩알뚜기" },
  { "OBLIVION WING", "데스윙" },
  { "OBSTAGOON", "가로막구리" },
  { "OBSTRUCT", "블로킹" },
  { "OCTAZOOKA", "대포무노포" },
  { "OCTILLERY", "대포무노" },
  { "OCTOLOCK", "문어굳히기" },
  { "ODDISH", "뚜벅쵸" },
  { "ODOR SLEUTH", "냄새구별" },
  { "OGERPON", "오거폰" },
  { "OINKOLOGNE", "퍼퓨돈" },
  { "OK", "확인" },
  { "OKIDOGI", "조타구" },
  { "OLIVIA", "라이치" },
  { "OLIVINE", "담청시티" },
  { "OLYMPIA", "고지카" },
  { "OMANYTE", "암나이트" },
  { "OMASTAR", "암스타" },
  { "ONIX", "롱스톤" },
  { "OPELUCID", "쌍용시티" },
  { "ORANGURU", "하랑우탄" },
  { "ORBEETLE", "이올브" },
  { "ORDER UP", "한판내기" },
  { "OREBURGH", "무쇠시티" },
  { "ORICORIO", "춤추새" },
  { "ORIGIN PULSE", "근원의파동" },
  { "ORTHWORM", "꿈트렁" },
  { "OSHAWOTT", "수댕이" },
  { "OUTRAGE", "역린" },
  { "OVERDRIVE", "오버드라이브" },
  { "OVERHEAT", "오버히트" },
  { "OVERQWIL", "장침바루" },
  { "PACHIRISU", "파치리스" },
  { "PAIN SPLIT", "아픔나누기" },
  { "PALAFIN", "돌핀맨" },
  { "PALDEA", "팔데아" },
  { "PALKIA", "펄기아" },
  { "PALOSSAND", "모래성이당" },
  { "PALPITOAD", "두까비" },
  { "PANCHAM", "판짱" },
  { "PANGORO", "부란다" },
  { "PANPOUR", "앗차프" },
  { "PANSAGE", "야나프" },
  { "PANSEAR", "바오프" },
  { "PARABOLIC CHARGE", "파라볼라차지" },
  { "PARAS", "파라스" },
  { "PARASECT", "파라섹트" },
  { "PARTING SHOT", "막말내뱉기" },
  { "PASSIMIAN", "내던숭이" },
  { "PASTORIA", "들판시티" },
  { "PATRAT", "보르쥐" },
  { "PAWMI", "빠모" },
  { "PAWMO", "빠모트" },
  { "PAWMOT", "빠르모트" },
  { "PAWNIARD", "자망칼" },
  { "PAY DAY", "고양이돈받기" },
  { "PAYBACK", "보복" },
  { "PECHARUNT", "복숭악동" },
  { "PECK", "쪼기" },
  { "PELIPPER", "패리퍼" },
  { "PERISH SONG", "멸망의노래" },
  { "PERRSERKER", "나이킹" },
  { "PERSIAN", "페르시온" },
  { "PETAL BLIZZARD", "꽃보라" },
  { "PETAL DANCE", "꽃잎댄스" },
  { "PETALBURG", "등화시티" },
  { "PETILIL", "치릴리" },
  { "PEWTER", "회색시티" },
  { "PHANPY", "코코리" },
  { "PHANTOM FORCE", "고스트다이브" },
  { "PHANTUMP", "나목령" },
  { "PHEROMOSA", "페로코체" },
  { "PHIONE", "피오네" },
  { "PHOEBE", "회연" },
  { "PHOTON GEYSER", "포톤가이저" },
  { "PICHU", "피츄" },
  { "PIDGEOT", "피죤투" },
  { "PIDGEOTTO", "피죤" },
  { "PIDGEY", "구구" },
  { "PIDOVE", "콩둘기" },
  { "PIGNITE", "차오꿀" },
  { "PIKACHU", "피카츄" },
  { "PIKIPEK", "콕코구리" },
  { "PILOSWINE", "메꾸리" },
  { "PIN MISSILE", "바늘미사일" },
  { "PINCURCHIN", "찌르성게" },
  { "PINECO", "피콘" },
  { "PINSIR", "쁘사이저" },
  { "PIPLUP", "팽도리" },
  { "PLASMA FISTS", "플라스마피스트" },
  { "PLAY NICE", "친해지기" },
  { "PLAY ROUGH", "치근거리기" },
  { "PLUCK", "쪼아대기" },
  { "PLUSLE", "플러시" },
  { "POIPOLE", "베베놈" },
  { "POISON", "독" },
  { "POISON FANG", "맹독엄니" },
  { "POISON GAS", "독가스" },
  { "POISON JAB", "독찌르기" },
  { "POISON POWDER", "독가루" },
  { "POISON STING", "독침" },
  { "POISON TAIL", "포이즌테일" },
  { "POLITOED", "왕구리" },
  { "POLIWAG", "발챙이" },
  { "POLIWHIRL", "슈륙챙이" },
  { "POLIWRATH", "강챙이" },
  { "POLLEN PUFF", "꽃가루경단" },
  { "POLTCHAGEIST", "차데스" },
  { "POLTEAGEIST", "포트데스" },
  { "PONI", "포니섬" },
  { "PONYTA", "포니타" },
  { "POOCHYENA", "포챠나" },
  { "POPPLIO", "누리공" },
  { "POPULATION BOMB", "찍찍베기" },
  { "PORYGON", "폴리곤" },
  { "PORYGON Z", "폴리곤Z" },
  { "PORYGON2", "폴리곤2" },
  { "POUND", "막치기" },
  { "POWDER SNOW", "눈싸라기" },
  { "POWER GEM", "파워젬" },
  { "POWER SPLIT", "파워셰어" },
  { "POWER SWAP", "파워스왑" },
  { "POWER TRICK", "파워트릭" },
  { "POWER TRIP", "기어오르기" },
  { "POWER WHIP", "파워휩" },
  { "POWER-UP PUNCH", "그로우펀치" },
  { "PRECIPICE BLADES", "단애의칼" },
  { "PRESENT", "프레젠트" },
  { "PRIMARINA", "누리레느" },
  { "PRIMEAPE", "성원숭" },
  { "PRINPLUP", "팽태자" },
  { "PRISMATIC LASER", "프리즘레이저" },
  { "PROBOPASS", "대코파스" },
  { "PROTECT", "방어" },
  { "PRYCE", "류옹" },
  { "PSYBEAM", "환상빔" },
  { "PSYBLADE", "사이코블레이드" },
  { "PSYCH UP", "자기암시" },
  { "PSYCHIC", "사이코키네시스" },
  { "PSYCHIC FANGS", "사이코팽" },
  { "PSYCHIC TERRAIN", "사이코필드" },
  { "PSYCHO BOOST", "사이코부스트" },
  { "PSYCHO CUT", "사이코커터" },
  { "PSYCHO SHIFT", "사이코시프트" },
  { "PSYDUCK", "고라파덕" },
  { "PSYSHIELD BASH", "배리어러시" },
  { "PSYSHOCK", "사이코쇼크" },
  { "PSYSTRIKE", "사이코브레이크" },
  { "PSYWAVE", "사이코웨이브" },
  { "PUMPKABOO", "호바귀" },
  { "PUPITAR", "데기라스" },
  { "PURIFY", "정화" },
  { "PURRLOIN", "쌔비냥" },
  { "PURUGLY", "몬냥이" },
  { "PYRO BALL", "화염볼" },
  { "PYROAR", "화염레오" },
  { "PYUKUMUKU", "해무기" },
  { "QUAGSIRE", "누오" },
  { "QUAQUAVAL", "웨이니발" },
  { "QUASH", "순서미루기" },
  { "QUAXLY", "꾸왁스" },
  { "QUAXWELL", "아꾸왁" },
  { "QUICK ATTACK", "전광석화" },
  { "QUICK GUARD", "패스트가드" },
  { "QUILAVA", "마그케인" },
  { "QUILLADIN", "도치보구" },
  { "QUIVER DANCE", "나비춤" },
  { "QWILFISH", "침바루" },
  { "RABOOT", "래비풋" },
  { "RABSCA", "베라카스" },
  { "RAGE FIST", "분노의주먹" },
  { "RAGE POWDER", "분노가루" },
  { "RAGING BOLT", "날뛰는우레" },
  { "RAGING BULL", "레이징불" },
  { "RAGING FURY", "대격분" },
  { "RAICHU", "라이츄" },
  { "RAIKOU", "라이코" },
  { "RAIN DANCE", "비바라기" },
  { "RALTS", "랄토스" },
  { "RAMOS", "후쿠지" },
  { "RAMPARDOS", "램펄드" },
  { "RAPID SPIN", "고속스핀" },
  { "RAPIDASH", "날쌩마" },
  { "RATICATE", "레트라" },
  { "RATTATA", "꼬렛" },
  { "RAYQUAZA", "레쿠쟈" },
  { "RAZOR LEAF", "잎날가르기" },
  { "RAZOR SHELL", "셸블레이드" },
  { "RECOVER", "HP회복" },
  { "RECYCLE", "리사이클" },
  { "RED", "레드" },
  { "REFLECT", "리플렉터" },
  { "REFLECT TYPE", "미러타입" },
  { "REGICE", "레지아이스" },
  { "REGIDRAGO", "레지드래고" },
  { "REGIELEKI", "레지에레키" },
  { "REGIGIGAS", "레지기가스" },
  { "REGIROCK", "레지락" },
  { "REGISTEEL", "레지스틸" },
  { "RELIC SONG", "옛노래" },
  { "RELICANTH", "시라칸" },
  { "RELLOR", "구르데" },
  { "REMORAID", "총어" },
  { "RESHIRAM", "레시라무" },
  { "REST", "잠자기" },
  { "RETALIATE", "원수갚기" },
  { "REUNICLUS", "란쿨루스" },
  { "REVAVROOM", "부르르룸" },
  { "REVELATION DANCE", "잠재댄스" },
  { "REVENGE", "리벤지" },
  { "REVERSAL", "기사회생" },
  { "REVIVAL BLESSING", "회생의기도" },
  { "RHYDON", "코뿌리" },
  { "RHYHORN", "뿔카노" },
  { "RHYPERIOR", "거대코뿌리" },
  { "RIBOMBEE", "에리본" },
  { "RILLABOOM", "고릴타" },
  { "RIOLU", "리오르" },
  { "RISING VOLTAGE", "라이징볼트" },
  { "RIVAL", "라이벌" },
  { "ROAR", "울부짖기" },
  { "ROAR OF TIME", "시간의포효" },
  { "ROARING MOON", "고동치는달" },
  { "ROARK", "강석" },
  { "ROCK", "바위" },
  { "ROCK BLAST", "록블라스트" },
  { "ROCK POLISH", "록커트" },
  { "ROCK SLIDE", "스톤샤워" },
  { "ROCK SMASH", "바위깨기" },
  { "ROCK THROW", "돌떨구기" },
  { "ROCK TOMB", "암석봉인" },
  { "ROCK WRECKER", "암석포" },
  { "ROCKRUFF", "암멍이" },
  { "ROGGENROLA", "단굴" },
  { "ROLE PLAY", "역할" },
  { "ROLLOUT", "구르기" },
  { "ROLYCOLY", "탄동" },
  { "ROOKIDEE", "파라꼬" },
  { "ROOST", "날개쉬기" },
  { "ROSELIA", "로젤리아" },
  { "ROSERADE", "로즈레이드" },
  { "ROTOM", "로토무" },
  { "ROTOTILLER", "일구기" },
  { "ROUND", "돌림노래" },
  { "ROWLET", "나몰빼미" },
  { "ROXANNE", "원규" },
  { "ROXIE", "보미카" },
  { "RUFFLET", "수리둥보" },
  { "RUINATION", "카타스트로피" },
  { "RUNERIGUS", "데스판" },
  { "RUSTBORO", "금탄시티" },
  { "SABLEYE", "깜까미" },
  { "SABRINA", "초련" },
  { "SACRED FIRE", "성스러운불꽃" },
  { "SACRED SWORD", "성스러운칼" },
  { "SAFEGUARD", "신비의부적" },
  { "SAFFRON", "노랑시티" },
  { "SAILOR", "선원" },
  { "SALAMENCE", "보만다" },
  { "SALANDIT", "야도뇽" },
  { "SALAZZLE", "염뉴트" },
  { "SALT CURE", "소금절이" },
  { "SAMUROTT", "대검귀" },
  { "SAND ATTACK", "모래뿌리기" },
  { "SAND TOMB", "모래지옥" },
  { "SANDACONDA", "사다이사" },
  { "SANDILE", "깜눈크" },
  { "SANDSEAR STORM", "열사의폭풍" },
  { "SANDSHREW", "모래두지" },
  { "SANDSLASH", "고지" },
  { "SANDSTORM", "모래바람" },
  { "SANDY SHOCKS", "모래털가죽" },
  { "SANDYGAST", "모래꿍" },
  { "SANTALUNE", "백단시티" },
  { "SAWK", "타격귀" },
  { "SAWSBUCK", "바라철록" },
  { "SCALD", "열탕" },
  { "SCARY FACE", "겁나는얼굴" },
  { "SCATTERBUG", "분이벌레" },
  { "SCEPTILE", "나무킹" },
  { "SCIZOR", "핫삼" },
  { "SCOLIPEDE", "펜드라" },
  { "SCORBUNNY", "염버니" },
  { "SCOVILLAIN", "스코빌런" },
  { "SCRAFTY", "곤율거니" },
  { "SCRAGGY", "곤율랭" },
  { "SCRATCH", "할퀴기" },
  { "SCREAM TAIL", "우렁찬꼬리" },
  { "SCREECH", "싫은소리" },
  { "SCYTHER", "스라크" },
  { "SEADRA", "시드라" },
  { "SEAKING", "왕콘치" },
  { "SEALEO", "씨레오" },
  { "SEARING SHOT", "화염탄" },
  { "SECRET SWORD", "신비의칼" },
  { "SEED BOMB", "씨폭탄" },
  { "SEED FLARE", "시드플레어" },
  { "SEEDOT", "도토링" },
  { "SEEL", "쥬쥬" },
  { "SEISMIC TOSS", "지구던지기" },
  { "SEISMITOAD", "두빅굴" },
  { "SELF-DESTRUCT", "자폭" },
  { "SENTRET", "꼬리선" },
  { "SERPERIOR", "샤로다" },
  { "SERVINE", "샤비" },
  { "SEVIPER", "세비퍼" },
  { "SEWADDLE", "두르보" },
  { "SHADOW BALL", "섀도볼" },
  { "SHADOW CLAW", "섀도클로" },
  { "SHADOW FORCE", "섀도다이브" },
  { "SHADOW PUNCH", "섀도펀치" },
  { "SHADOW SNEAK", "야습" },
  { "SHALOUR", "사라시티" },
  { "SHARPEDO", "샤크니아" },
  { "SHAUNTAL", "망초" },
  { "SHAYMIN", "쉐이미" },
  { "SHED TAIL", "꼬리자르기" },
  { "SHEDINJA", "껍질몬" },
  { "SHEER COLD", "절대영도" },
  { "SHELGON", "쉘곤" },
  { "SHELL SMASH", "껍질깨기" },
  { "SHELL TRAP", "트랩셸" },
  { "SHELLDER", "셀러" },
  { "SHELLOS", "깝질무" },
  { "SHELMET", "쪼마리" },
  { "SHIELDON", "방패톱스" },
  { "SHIFT GEAR", "기어체인지" },
  { "SHIFTRY", "다탱구" },
  { "SHIINOTIC", "마셰이드" },
  { "SHINX", "꼬링크" },
  { "SHOCK WAVE", "전격파" },
  { "SHORE UP", "모래모으기" },
  { "SHROODLE", "땃쭈르" },
  { "SHROOMISH", "버섯꼬" },
  { "SHUCKLE", "단단지" },
  { "SHUPPET", "어둠대신" },
  { "SIDNEY", "혁진" },
  { "SIEBOLD", "즈미" },
  { "SIGILYPH", "심보러" },
  { "SILCOON", "실쿤" },
  { "SILICOBRA", "모래뱀" },
  { "SILK TRAP", "스레드트랩" },
  { "SILVALLY", "실버디" },
  { "SILVER WIND", "은빛바람" },
  { "SIMIPOUR", "앗차키" },
  { "SIMISAGE", "야나키" },
  { "SIMISEAR", "바오키" },
  { "SIMPLE BEAM", "심플빔" },
  { "SING", "노래하기" },
  { "SINISTCHA", "그우린차" },
  { "SINISTEA", "데인차" },
  { "SINNOH", "신오" },
  { "SIRFETCH'D", "창파나이트" },
  { "SIZZLIPEDE", "태우지네" },
  { "SKARMORY", "무장조" },
  { "SKELEDIRGE", "라우드본" },
  { "SKETCH", "스케치" },
  { "SKIDDO", "메이클" },
  { "SKILL SWAP", "스킬스왑" },
  { "SKIPLOOM", "두코" },
  { "SKITTER SMACK", "엄습하는일격" },
  { "SKITTY", "에나비" },
  { "SKORUPI", "스콜피" },
  { "SKRELP", "수레기" },
  { "SKULL BASH", "로켓박치기" },
  { "SKUNTANK", "스컹탱크" },
  { "SKWOVET", "탐리스" },
  { "SKY ATTACK", "불새" },
  { "SKYLA", "풍란" },
  { "SLACK OFF", "게으름피우기" },
  { "SLAKING", "게을킹" },
  { "SLAKOTH", "게을로" },
  { "SLAM", "힘껏치기" },
  { "SLASH", "베어가르기" },
  { "SLEEP POWDER", "수면가루" },
  { "SLEEP TALK", "잠꼬대" },
  { "SLIGGOO", "미끄네일" },
  { "SLITHER WING", "땅을기는날개" },
  { "SLOWBRO", "야도란" },
  { "SLOWKING", "야도킹" },
  { "SLOWPOKE", "야돈" },
  { "SLUDGE", "오물공격" },
  { "SLUDGE BOMB", "오물폭탄" },
  { "SLUDGE WAVE", "오물웨이브" },
  { "SLUGMA", "마그마그" },
  { "SLURPUFF", "나루림" },
  { "SMACK DOWN", "떨어뜨리기" },
  { "SMART STRIKE", "스마트혼" },
  { "SMEARGLE", "루브도" },
  { "SMOG", "스모그" },
  { "SMOKESCREEN", "연막" },
  { "SMOLIV", "미니브" },
  { "SMOOCHUM", "뽀뽀라" },
  { "SNARL", "바크아웃" },
  { "SNEASEL", "포푸니" },
  { "SNEASLER", "포푸니크" },
  { "SNIPE SHOT", "노려맞히기" },
  { "SNIVY", "주리비얀" },
  { "SNOM", "누니머기" },
  { "SNORE", "코골기" },
  { "SNORLAX", "잠만보" },
  { "SNORUNT", "눈꼬마" },
  { "SNOVER", "눈쓰개" },
  { "SNOWBELLE", "이설시티" },
  { "SNOWPOINT", "선단시티" },
  { "SNOWSCAPE", "설경" },
  { "SNUBBULL", "블루" },
  { "SOAK", "물붓기" },
  { "SOBBLE", "울머기" },
  { "SOFT-BOILED", "알낳기" },
  { "SOLAR BEAM", "솔라빔" },
  { "SOLAR BLADE", "솔라블레이드" },
  { "SOLGALEO", "솔가레오" },
  { "SOLOSIS", "유니란" },
  { "SOLROCK", "솔록" },
  { "SOOTOPOLIS", "루네시티" },
  { "SOPHOCLES", "마마네" },
  { "SPACIAL REND", "공간절단" },
  { "SPARK", "스파크" },
  { "SPARKLING ARIA", "물거품아리아" },
  { "SPEAROW", "깨비참" },
  { "SPECTRAL THIEF", "섀도스틸" },
  { "SPECTRIER", "레이스포스" },
  { "SPEED SWAP", "스피드스왑" },
  { "SPEWPA", "분떠도리" },
  { "SPHEAL", "대굴레오" },
  { "SPICY EXTRACT", "하바네로엑기스" },
  { "SPIDOPS", "트래피더" },
  { "SPIKES", "압정뿌리기" },
  { "SPIKY SHIELD", "니들가드" },
  { "SPIN OUT", "휠스핀" },
  { "SPINARAK", "페이검" },
  { "SPINDA", "얼루기" },
  { "SPIRIT BREAK", "소울크래시" },
  { "SPIRIT SHACKLE", "그림자꿰매기" },
  { "SPIRITOMB", "화강돌" },
  { "SPIT UP", "토해내기" },
  { "SPITE", "원한" },
  { "SPLASH", "튀어오르기" },
  { "SPOINK", "피그점프" },
  { "SPORE", "버섯포자" },
  { "SPRIGATITO", "나오하" },
  { "SPRINGTIDE STORM", "봄의폭풍" },
  { "SPRITZEE", "슈쁘" },
  { "SQUAWKABILLY", "시비꼬" },
  { "SQUIRTLE", "꼬부기" },
  { "STAB", "자속" },
  { "STAKATAKA", "차곡차곡" },
  { "STANTLER", "노라키" },
  { "STARAPTOR", "찌르호크" },
  { "STARAVIA", "찌르버드" },
  { "STARLY", "찌르꼬" },
  { "STARMIE", "아쿠스타" },
  { "STARYU", "별가사리" },
  { "STEALTH ROCK", "스텔스록" },
  { "STEAM ERUPTION", "스팀버스트" },
  { "STEEL", "강철" },
  { "STEEL ROLLER", "아이언롤러" },
  { "STEEL WING", "강철날개" },
  { "STEELIX", "강철톤" },
  { "STEENEE", "달무리나" },
  { "STICKY WEB", "끈적끈적네트" },
  { "STOCKPILE", "비축하기" },
  { "STOMP", "짓밟기" },
  { "STOMPING TANTRUM", "분함의발구르기" },
  { "STONE AXE", "암석액스" },
  { "STONE EDGE", "스톤에지" },
  { "STONJOURNER", "돌헨진" },
  { "STORED POWER", "어시스트파워" },
  { "STORM THROW", "업어후리기" },
  { "STOUTLAND", "바랜드" },
  { "STRENGTH", "괴력" },
  { "STRENGTH SAP", "힘흡수" },
  { "STRING SHOT", "실뿜기" },
  { "STRUGGLE", "발버둥" },
  { "STRUGGLE BUG", "벌레의저항" },
  { "STUFF CHEEKS", "볼가득넣기" },
  { "STUFFUL", "포곰곰" },
  { "STUN SPORE", "저리가루" },
  { "STUNFISK", "메더" },
  { "STUNKY", "스컹뿡" },
  { "SUBMISSION", "지옥의바퀴" },
  { "SUBSTITUTE", "대타출동" },
  { "SUCKER PUNCH", "기습" },
  { "SUDOWOODO", "꼬지모" },
  { "SUICUNE", "스이쿤" },
  { "SUNFLORA", "해루미" },
  { "SUNKERN", "해너츠" },
  { "SUNNY DAY", "쾌청" },
  { "SUNSTEEL STRIKE", "메테오드라이브" },
  { "SUNYSHORE", "물가시티" },
  { "SUPER FANG", "분노의앞니" },
  { "SUPERPOWER", "엄청난힘" },
  { "SUPERSONIC", "초음파" },
  { "SURF", "파도타기" },
  { "SURSKIT", "비구술" },
  { "SWABLU", "파비코" },
  { "SWADLOON", "두르쿤" },
  { "SWAGGER", "뽐내기" },
  { "SWALLOW", "꿀꺽" },
  { "SWALOT", "꿀꺽몬" },
  { "SWAMPERT", "대짱이" },
  { "SWANNA", "스완나" },
  { "SWEET KISS", "천사의키스" },
  { "SWEET SCENT", "달콤한향기" },
  { "SWELLOW", "스왈로" },
  { "SWIFT", "스피드스타" },
  { "SWINUB", "꾸꾸리" },
  { "SWIRLIX", "나룸퍼프" },
  { "SWITCHEROO", "바꿔치기" },
  { "SWOOBAT", "맘박쥐" },
  { "SWORDS DANCE", "칼춤" },
  { "SYLVEON", "님피아" },
  { "SYNTHESIS", "광합성" },
  { "SYRUP BOMB", "시럽봄" },
  { "TACHYON CUTTER", "타키온커터" },
  { "TACKLE", "몸통박치기" },
  { "TADBULB", "빈나두" },
  { "TAIL GLOW", "반딧불" },
  { "TAIL SLAP", "스위프뺨치기" },
  { "TAIL WHIP", "꼬리흔들기" },
  { "TAILLOW", "테일로" },
  { "TAILWIND", "순풍" },
  { "TAKE DOWN", "돌진" },
  { "TAKE HEART", "브레이브차지" },
  { "TALONFLAME", "파이어로" },
  { "TANDEMAUS", "두리쥐" },
  { "TANGELA", "덩쿠리" },
  { "TANGROWTH", "덩쿠림보" },
  { "TAPU BULU", "카푸브루루" },
  { "TAPU FINI", "카푸느지느" },
  { "TAPU KOKO", "카푸꼬꼬꼭" },
  { "TAPU LELE", "카푸나비나" },
  { "TAR SHOT", "타르샷" },
  { "TAROUNTULA", "타랜툴라" },
  { "TATE", "풍" },
  { "TATSUGIRI", "싸리용" },
  { "TAUNT", "도발" },
  { "TAUROS", "켄타로스" },
  { "TEARFUL LOOK", "눈물그렁그렁" },
  { "TEATIME", "다과회" },
  { "TECHNO BLAST", "테크노버스터" },
  { "TEDDIURSA", "깜지곰" },
  { "TEETER DANCE", "흔들흔들댄스" },
  { "TELEPORT", "순간이동" },
  { "TENTACOOL", "왕눈해" },
  { "TENTACRUEL", "독파리" },
  { "TEPIG", "뚜꾸리" },
  { "TERA STARSTORM", "테라클러스터" },
  { "TERAPAGOS", "테라파고스" },
  { "TERRAIN PULSE", "대지의파동" },
  { "TERRAKION", "테라키온" },
  { "THIEF", "도둑질" },
  { "THIEVUL", "폭슬라이" },
  { "THOUSAND ARROWS", "사우전드애로" },
  { "THOUSAND WAVES", "사우전드웨이브" },
  { "THRASH", "난동부리기" },
  { "THROAT CHOP", "지옥찌르기" },
  { "THROH", "던지미" },
  { "THUNDER", "번개" },
  { "THUNDER CAGE", "썬더프리즌" },
  { "THUNDER FANG", "번개엄니" },
  { "THUNDER WAVE", "전기자석파" },
  { "THUNDERBOLT", "10만볼트" },
  { "THUNDERCLAP", "질풍신뢰" },
  { "THUNDERPUNCH", "번개펀치" },
  { "THUNDERSHOCK", "전기쇼크" },
  { "THUNDURUS", "볼트로스" },
  { "THWACKEY", "채키몽" },
  { "TICKLE", "간지르기" },
  { "TIDY UP", "정리정돈" },
  { "TIMBURR", "으랏차" },
  { "TING-LU", "딩루" },
  { "TINKATINK", "어리짱" },
  { "TINKATON", "두드리짱" },
  { "TINKATUFF", "벼리짱" },
  { "TIRTOUGA", "프로토가" },
  { "TOEDSCOOL", "들눈해" },
  { "TOEDSCRUEL", "육파리" },
  { "TOGEDEMARU", "토게데마루" },
  { "TOGEKISS", "토게키스" },
  { "TOGEPI", "토게피" },
  { "TOGETIC", "토게틱" },
  { "TOPSY-TURVY", "뒤집어엎기" },
  { "TORCH SONG", "플레어송" },
  { "TORCHIC", "아차모" },
  { "TORKOAL", "코터스" },
  { "TORMENT", "트집" },
  { "TORNADUS", "토네로스" },
  { "TORRACAT", "냐오히트" },
  { "TORTERRA", "토대부기" },
  { "TOTODILE", "리아코" },
  { "TOUCANNON", "왕큰부리" },
  { "TOXAPEX", "더시마사리" },
  { "TOXEL", "일레즌" },
  { "TOXIC", "맹독" },
  { "TOXIC SPIKES", "독압정" },
  { "TOXIC THREAD", "독실" },
  { "TOXICROAK", "독개굴" },
  { "TOXTRICITY", "스트린더" },
  { "TRANQUILL", "유토브" },
  { "TRANSFORM", "변신" },
  { "TRAPINCH", "톱치" },
  { "TREECKO", "나무지기" },
  { "TREVENANT", "대로트" },
  { "TRI ATTACK", "트라이어택" },
  { "TRICK", "트릭" },
  { "TRICK ROOM", "트릭룸" },
  { "TRICK-OR-TREAT", "핼러윈" },
  { "TRIPLE DIVE", "트리플다이브" },
  { "TRIPLE KICK", "트리플킥" },
  { "TROP KICK", "트로피컬킥" },
  { "TROPIUS", "트로피우스" },
  { "TRUBBISH", "깨봉이" },
  { "TRUMBEAK", "크라파" },
  { "TSAREENA", "달코퀸" },
  { "TURTONATOR", "폭거북스" },
  { "TURTWIG", "모부기" },
  { "TWIN BEAM", "트윈빔" },
  { "TWISTER", "회오리" },
  { "TYMPOLE", "동챙이" },
  { "TYNAMO", "저리어" },
  { "TYPE NULL", "타입:널" },
  { "TYPHLOSION", "블레이범" },
  { "TYRANITAR", "마기라스" },
  { "TYRANTRUM", "견고라스" },
  { "TYROGUE", "배루키" },
  { "TYRUNT", "티고라스" },
  { "U-TURN", "유턴" },
  { "ULAULA", "울라울라섬" },
  { "UMBREON", "블래키" },
  { "UNFEZANT", "켄호로우" },
  { "UNOVA", "하나" },
  { "UNOWN", "안농" },
  { "UPROAR", "소란피기" },
  { "URSALUNA", "다투곰" },
  { "URSARING", "링곰" },
  { "URSHIFU", "우라오스" },
  { "UXIE", "유크시" },
  { "V-CREATE", "V제너레이트" },
  { "VACUUM WAVE", "진공파" },
  { "VALERIE", "마슈" },
  { "VANILLISH", "바닐리치" },
  { "VANILLITE", "바닐프티" },
  { "VANILLUXE", "배바닐라" },
  { "VAPOREON", "샤미드" },
  { "VAROOM", "부르롱" },
  { "VEILSTONE", "장막시티" },
  { "VELUZA", "가비루사" },
  { "VENIPEDE", "마디네" },
  { "VENOM DRENCH", "베놈트랩" },
  { "VENOMOTH", "도나리" },
  { "VENONAT", "콘팡" },
  { "VENOSHOCK", "베놈쇼크" },
  { "VENUSAUR", "이상해꽃" },
  { "VERMILION", "갈색시티" },
  { "VESPIQUEN", "비퀸" },
  { "VIBRAVA", "비브라바" },
  { "VICTINI", "비크티니" },
  { "VICTREEBEL", "우츠보트" },
  { "VIGOROTH", "발바로" },
  { "VIKAVOLT", "투구뿌논" },
  { "VILEPLUME", "라플레시아" },
  { "VINE WHIP", "덩굴채찍" },
  { "VIOLA", "비올라" },
  { "VIOLET", "도라지시티" },
  { "VIRBANK", "모란만시티" },
  { "VIRIDIAN", "상록시티" },
  { "VIRIZION", "비리디온" },
  { "VISE GRIP", "찝기" },
  { "VITAL THROW", "받아던지기" },
  { "VIVILLON", "비비용" },
  { "VOLBEAT", "볼비트" },
  { "VOLCANION", "볼케니온" },
  { "VOLCARONA", "불카모스" },
  { "VOLKNER", "전진" },
  { "VOLT SWITCH", "볼트체인지" },
  { "VOLTORB", "찌리리공" },
  { "VULLABY", "벌차이" },
  { "VULPIX", "식스테일" },
  { "WAILMER", "고래왕자" },
  { "WAILORD", "고래왕" },
  { "WAKE", "맥실러" },
  { "WALKING WAKE", "굽이치는물결" },
  { "WALLACE", "윤진" },
  { "WALREIN", "씨카이저" },
  { "WARTORTLE", "어니부기" },
  { "WATCHOG", "보르그" },
  { "WATER", "물" },
  { "WATER GUN", "물대포" },
  { "WATER PULSE", "물의파동" },
  { "WATER SHURIKEN", "물수리검" },
  { "WATER SPORT", "물놀이" },
  { "WATER SPOUT", "해수스파우팅" },
  { "WATERFALL", "폭포오르기" },
  { "WATTREL", "찌리비" },
  { "WATTSON", "암페어" },
  { "WAVE CRASH", "웨이브태클" },
  { "WEATHER BALL", "웨더볼" },
  { "WEAVILE", "포푸니라" },
  { "WEEDLE", "뿔충이" },
  { "WEEPINBELL", "우츠동" },
  { "WEEZING", "또도가스" },
  { "WHIMSICOTT", "엘풍" },
  { "WHIRLIPEDE", "휠구" },
  { "WHIRLPOOL", "바다회오리" },
  { "WHIRLWIND", "날려버리기" },
  { "WHISCASH", "메깅" },
  { "WHISMUR", "소곤룡" },
  { "WHITNEY", "꼭두" },
  { "WICKED BLOW", "암흑강타" },
  { "WIDE GUARD", "와이드가드" },
  { "WIGGLYTUFF", "푸크린" },
  { "WIGLETT", "바다그다" },
  { "WIKSTROM", "간피" },
  { "WILD CHARGE", "와일드볼트" },
  { "WILDBOLT STORM", "번개폭풍" },
  { "WILL", "일목" },
  { "WILL-O-WISP", "도깨비불" },
  { "WIMPOD", "꼬시레" },
  { "WING ATTACK", "날개치기" },
  { "WINGULL", "갈모매" },
  { "WINONA", "은송" },
  { "WISH", "희망사항" },
  { "WISHIWASHI", "약어리" },
  { "WITHDRAW", "껍질에숨기" },
  { "WO-CHIEN", "총지엔" },
  { "WOBBUFFET", "마자용" },
  { "WONDER ROOM", "원더룸" },
  { "WOOBAT", "또르박쥐" },
  { "WOOD HAMMER", "우드해머" },
  { "WOOLOO", "우르" },
  { "WOOPER", "우파" },
  { "WORK UP", "분발" },
  { "WORMADAM", "도롱마담" },
  { "WORRY SEED", "고민씨" },
  { "WRAP", "김밥말이" },
  { "WUGTRIO", "바닥트리오" },
  { "WULFRIC", "우르프" },
  { "WURMPLE", "개무소" },
  { "WYNAUT", "마자" },
  { "WYRDEER", "신비록" },
  { "X-SCISSOR", "시저크로스" },
  { "XATU", "네이티오" },
  { "XERNEAS", "제르네아스" },
  { "XURKITREE", "전수목" },
  { "YAMASK", "데스마스" },
  { "YAMPER", "멍파치" },
  { "YANMA", "왕자리" },
  { "YANMEGA", "메가자리" },
  { "YAWN", "하품" },
  { "YOUNGSTER", "반바지 꼬마" },
  { "YUNGOOS", "영구스" },
  { "YVELTAL", "이벨타르" },
  { "ZACIAN", "자시안" },
  { "ZAMAZENTA", "자마젠타" },
  { "ZANGOOSE", "쟝고" },
  { "ZAP CANNON", "전자포" },
  { "ZAPDOS", "썬더" },
  { "ZARUDE", "자루도" },
  { "ZEBSTRIKA", "제브라이카" },
  { "ZEKROM", "제크로무" },
  { "ZEN HEADBUTT", "사념의박치기" },
  { "ZERAORA", "제라오라" },
  { "ZIGZAGOON", "지그제구리" },
  { "ZING ZAP", "찌리리따끔따끔" },
  { "ZOROARK", "조로아크" },
  { "ZORUA", "조로아" },
  { "ZUBAT", "주뱃" },
  { "ZWEILOUS", "디헤드" },
  { "ZYGARDE", "지가르데" },
  { "tap...", "누르세요" },
};
