// GENERATED by tools/check_sprites.py --emit. Do not edit.
//
// Species SpriteCollab has no usable base or approved fallback-form art.
// Approved alternate forms are listed in tools/pmd_forms.py. They KEEP
// THEIR DEX NUMBERS -- removing one would renumber every species after it, and
// dex numbers are positional in saved data (dexReg bits, speciesId,
// every party record) -- but they are kept out of the egg pool, since
// hatching one gives a creature that can only ever draw as a number.
//
// Re-run after any expansion, and again if upstream adds art.
#pragma once

#define NO_ART_COUNT 43
static const int16_t NO_ART[NO_ART_COUNT ? NO_ART_COUNT : 1] = {
  514, 516, 520, 522, 523, 538, 558, 564, 565, 591, 592, 616, 626, 732, 735, 756, 765, 837, 838, 839, 847, 866, 878, 893, 896, 931, 942, 943, 944, 947, 949, 950, 954, 956, 962, 973, 986, 993, 1001, 1002, 1014, 1022, 1023
};

static inline bool speciesHasArt(int16_t d) {
  for (int i = 0; i < NO_ART_COUNT; i++)
    if (NO_ART[i] == d) return false;
  return true;
}

// Species that cannot hatch: the art-less entries above plus every
// earlier member whose evolution line can reach one of them.
#define NO_HATCH_COUNT 58
static const int16_t NO_HATCH[NO_HATCH_COUNT ? NO_HATCH_COUNT : 1] = {
  122, 439, 513, 514, 515, 516, 519, 520, 522, 523, 538, 557, 558, 564, 565, 590, 591, 592, 616, 626, 731, 732, 734, 735, 755, 756, 765, 837, 838, 839, 846, 847, 866, 878, 893, 896, 931, 942, 943, 944, 946, 947, 948, 949, 950, 953, 954, 955, 956, 962, 973, 986, 993, 1001, 1002, 1014, 1022, 1023
};

static inline bool speciesCanHatch(int16_t d) {
  for (int i = 0; i < NO_HATCH_COUNT; i++)
    if (NO_HATCH[i] == d) return false;
  return true;
}
