#!/usr/bin/env python3
"""Generate display-only body sizes; never change DexEntry or saved IDs.

Import a PokeAPI pokemon.csv snapshot with --source, then regenerate offline
from the compact, checked-in JSON using no arguments. Heights are decimetres.
"""
import argparse, csv, hashlib, json
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
p=argparse.ArgumentParser()
p.add_argument('--source',type=Path)
a=p.parse_args()
path=ROOT/'data/sprite_sizes.json'
if a.source:
    raw=a.source.read_bytes()
    rows=list(csv.DictReader(raw.decode('utf-8').splitlines()))
    names={r['identifier']:r for r in rows}
    defaults={int(r['species_id']):r for r in rows if r['is_default']=='1'}
    heights=[0]+[int(defaults[d]['height']) for d in range(1,1026)]
    forms=[]
    for f in json.loads((ROOT/'data/forms/catalog.json').read_text(encoding='utf-8'))['entries']:
        if not (f['normal_body_verified'] and f.get('normal_animated')): continue
        row=names.get(f['key'])
        if row is not None: assert int(row['species_id'])==f['dex'],f['key']
        forms.append({'dex':f['dex'],'form':f['form_id'],'key':f['key'],
                      'height_dm':int(row['height']) if row else heights[f['dex']],
                      'source':'form' if row else 'species-default'})
    data={'source':'https://raw.githubusercontent.com/PokeAPI/pokeapi/master/data/v2/csv/pokemon.csv',
          'source_sha256':hashlib.sha256(raw).hexdigest(),'retrieved':'2026-09-08',
          'height_dm':heights,'forms':forms}
    path.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
else:
    data=json.loads(path.read_text(encoding='utf-8'))
heights=data['height_dm']
assert len(heights)==1026 and all(h>0 for h in heights[1:])
lines=['// Generated by tools/gen_sprite_sizes.py from data/sprite_sizes.json.',
       '// Display metadata only. Source SHA-256: '+data['source_sha256'],
       '#pragma once','#include <stdint.h>','static const uint16_t SPRITE_HEIGHT_DM[1026] = {']
for i in range(0,len(heights),24):lines.append('  '+','.join(map(str,heights[i:i+24]))+',')
lines+=['};','struct SpriteFormHeight {uint16_t dex,form,height;};',
        'static const SpriteFormHeight SPRITE_FORM_HEIGHTS[] = {']
for f in data['forms']:lines.append('  {%d,%d,%d},'%(f['dex'],f['form'],f['height_dm']))
lines+=['};','']
(ROOT/'sprite_sizes.h').write_text('\n'.join(lines),encoding='utf-8')
print('Generated 1025 species and %d form display heights'%len(data['forms']))
print('Same-species fallback:',', '.join(f['key'] for f in data['forms'] if f['source']!='form'))
