#!/usr/bin/env python3
"""Build the flash-resident Galmuri11 subset. pip install Pillow fonttools."""
from pathlib import Path
import argparse, hashlib, json, re
from PIL import Image, ImageDraw, ImageFont
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parents[1]
FONT = ROOT / 'tools/fonts/Galmuri11.ttf'

def generate():
    # Includes local UI literals and all display names, but no web-only text.
    texts = [(ROOT / p).read_text(encoding='utf-8') for p in
             ('i18n.cpp', 'TamaPoke.ino', 'korean_names.h')]
    chars = sorted({c for s in texts for literal in re.findall(r'"([^"\n]*)"', s)
                    for c in literal if ord(c) > 127})
    cmap = TTFont(FONT).getBestCmap()
    missing = [c for c in chars if ord(c) not in cmap]
    if missing:
        raise SystemExit('Missing font glyphs: ' + ''.join(missing))
    font = ImageFont.truetype(str(FONT), 12)
    bitmaps = []
    for ch in chars:
        im = Image.new('1', (12, 12))
        box = font.getbbox(ch)
        ImageDraw.Draw(im).text(((12-(box[2]-box[0]))//2-box[0], -box[1]), ch, font=font, fill=1)
        bits = [im.getpixel((x, y)) != 0 for y in range(12) for x in range(12)]
        assert any(bits), f'Blank glyph: {ch}'
        bitmaps.append([sum(bits[i+j] << (7-j) for j in range(8)) for i in range(0,144,8)])
    out = '#pragma once\n// Generated by tools/gen_korean_font.py; Galmuri11, SIL OFL 1.1.\n#include <stdint.h>\n'
    out += f'#define KOREAN_GLYPH_COUNT {len(chars)}\n'
    out += 'static const uint32_t KOREAN_CODEPOINTS[] = {\n' + ','.join(str(ord(c)) for c in chars) + '\n};\n'
    out += 'static const uint8_t KOREAN_BITMAPS[][18] = {\n'
    out += ''.join('  {' + ','.join(f'0x{b:02x}' for b in row) + '},\n' for row in bitmaps) + '};\n'
    return out, {'glyphs': len(chars), 'bitmap_bytes':len(chars)*18,
                 'font_sha256':hashlib.sha256(FONT.read_bytes()).hexdigest(), 'characters':''.join(chars)}

if __name__ == '__main__':
    p=argparse.ArgumentParser(); p.add_argument('--check', action='store_true'); a=p.parse_args()
    out, info=generate(); target=ROOT/'korean_font.h'
    if a.check:
        assert target.read_text(encoding='utf-8') == out, 'Font is stale; regenerate it.'
    else:
        target.write_text(out,encoding='utf-8',newline='\n')
        (ROOT/'localization/font-coverage.json').write_text(json.dumps(info,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
    print(f"PASS: {info['glyphs']} Unicode glyphs, {info['bitmap_bytes']} bitmap bytes")
