#!/usr/bin/env python3
"""Generate the frozen per-species catch-rate table used by Explore.

The project already pins this PokeAPI data revision for its full move table.
Runtime builds never use the network; they compile the generated header.
"""
from __future__ import annotations

import argparse
import csv
import io
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DEX_COUNT = 1025
SOURCE_URL = (
    "https://raw.githubusercontent.com/PokeAPI/pokeapi/"
    "d4f9a4af58ade123fbc0558f68b1c69daa97d9e4/"
    "data/v2/csv/pokemon_species.csv"
)


def read_source(path: Path | None) -> str:
    if path:
        return path.read_text(encoding="utf-8")
    result = subprocess.run(
        ["curl", "-fsSL", SOURCE_URL], capture_output=True, check=True
    )
    return result.stdout.decode("utf-8")


def generate(source: str) -> str:
    rows = list(csv.DictReader(io.StringIO(source)))
    by_id = {int(row["id"]): int(row["capture_rate"]) for row in rows}
    missing = [dex for dex in range(1, DEX_COUNT + 1) if dex not in by_id]
    if missing:
        raise SystemExit(f"missing species rows: {missing[:10]}")
    invalid = [(dex, by_id[dex]) for dex in range(1, DEX_COUNT + 1)
               if not 1 <= by_id[dex] <= 255]
    if invalid:
        raise SystemExit(f"invalid catch rates: {invalid[:10]}")

    values = [0] + [by_id[dex] for dex in range(1, DEX_COUNT + 1)]
    lines = []
    for start in range(0, len(values), 16):
        chunk = values[start:start + 16]
        lines.append("  " + ", ".join(f"{value:3d}" for value in chunk) + ",")
    return (
        "#pragma once\n"
        "// Generated by tools/gen_catch_rates.py from the pinned PokeAPI species table.\n"
        "#include <stdint.h>\n"
        "#include \"dex.h\"\n\n"
        "static const uint8_t CATCH_RATE[DEX_COUNT + 1] = {\n"
        + "\n".join(lines)
        + "\n};\n\n"
        "static inline uint8_t catchRateForDex(int16_t dex) {\n"
        "  return (dex >= 1 && dex <= DEX_COUNT) ? CATCH_RATE[dex] : 0;\n"
        "}\n"
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", type=Path, help="use an already downloaded CSV")
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--out", type=Path, default=ROOT / "catch_rates.h")
    args = parser.parse_args()
    output = generate(read_source(args.source))
    if args.check:
        if not args.out.exists() or args.out.read_text(encoding="utf-8") != output:
            raise SystemExit("catch_rates.h is stale")
    else:
        args.out.write_text(output, encoding="utf-8", newline="\n")
    print(f"PASS: {DEX_COUNT} catch rates -> {args.out}")


if __name__ == "__main__":
    main()
