#!/usr/bin/env python3
"""Generate the supported form table from the checked-in, pinned catalogue.

--sprites copies verified local PMD conversions and writes a separate TPAK.
No network, no base-art substitution, no use of excluded appearance variants.
"""
import argparse, hashlib, json, shutil, struct, zlib
from pathlib import Path
R=Path(__file__).resolve().parents[1]
CLASSES=['MEGA','REGIONAL','PRIMAL','FUSION','MASK','SPECIAL','GIANT']
TYPE_KO=['노말','불꽃','물','전기','풀','얼음','격투','독','땅','비행','에스퍼','벌레','바위','고스트','드래곤','악','강철','페어리']

def supported(x):
    return x['normal_body_verified'] and x.get('normal_animated',False)

def shiny_supported(x):
    return x['shiny_body_verified'] and x.get('shiny_animated',False)
def display_name(x):
    if x['form_name_ko']: return x['form_name_ko']
    k=x['key']
    if x['classification']=='MEGA': return '메가'+x['species_ko']
    if k.endswith('-gmax'): return '거다이맥스'
    if '-hisui' in k: return '히스이의 모습'
    if '-paldea' in k:
        return {'combat':'팔데아 컴뱃종','blaze':'팔데아 블레이즈종','aqua':'팔데아 워터종'}.get(k.split('-')[-2],'팔데아의 모습')
    if k.startswith(('arceus-','silvally-')): return TYPE_KO[x['types'][0]]+'타입'
    return {'dialga-origin':'오리진폼','palkia-origin':'오리진폼','enamorus-therian':'영물폼','palafin-hero':'마이티폼','terapagos-terastal':'테라스탈폼'}.get(k,k)
def main():
    p=argparse.ArgumentParser();p.add_argument('--sprites',action='store_true');a=p.parse_args()
    raw=(R/'data/forms/catalog.json').read_bytes(); data=json.loads(raw)
    entries=[x for x in data['entries'] if supported(x)]
    if a.sprites and not (R/'build/forms/packs').exists():
        from unpack_sprites import unpack
        unpack(R/'web/forms.pak',R/'build/forms/recovered')
    lines=['// Generated by tools/gen_forms.py. Do not renumber IDs.','const FormEntry FORM_TBL[] = {']
    seen=set(); files=[]
    for x in entries:
        assert x['classification'] in CLASSES
        assert (x['dex'],x['form_id']) not in seen;seen.add((x['dex'],x['form_id']))
        assert x['level'] in [60,70,80]
        assert all(0<=s<=255 for s in x['stats'])
        name=display_name(x)
        vals=[x['dex'],x['form_id'],json.dumps(x['key']),json.dumps(name,ensure_ascii=False),CLASSES.index(x['classification']),x['level'],*x['types'],*x['stats'],int(shiny_supported(x))]
        lines.append('  { '+', '.join(map(str,vals))+' },')
        if not a.sprites: continue
        for shiny in [False,True] if shiny_supported(x) else [False]:
            name=f"p{'s' if shiny else ''}{x['dex']:03}f{x['form_id']:05}.bin"
            src=R/'build/forms/packs'/name
            if not src.exists(): src=R/'build/forms/recovered/mons'/name
            blob=src.read_bytes()
            assert blob[:4]==b'TPK2',src
            from audit_animation import animation_info
            assert animation_info(blob)['animated'],f'No animated action: {src}'
            if not shiny: assert hashlib.sha256(blob).hexdigest()==x['sha256'],src
            dest=R/'tools/sdcard/mons'/name;shutil.copy2(src,dest);files.append(dest)
    lines+=['};',f'const uint16_t FORM_COUNT = {len(entries)};',f'const uint16_t FORM_DATA_TAG = {zlib.crc32(raw)&65535};','']
    (R/'forms_data.h').write_text('\n'.join(lines),encoding='utf-8')
    if a.sprites:
        pack=R/'build/forms-runtime/forms.pak';pack.parent.mkdir(parents=True,exist_ok=True)
        with pack.open('wb') as out:
            out.write(b'TPAK'+struct.pack('<H',len(files)))
            for f in files:
                n=('mons/'+f.name).encode();out.write(bytes([len(n)])+n+struct.pack('<I',f.stat().st_size))
            for f in files: out.write(f.read_bytes())
        print(pack,pack.stat().st_size)
        shutil.copy2(pack,R/'web/forms.pak')
    print(f'{len(entries)} supported forms generated')
if __name__=='__main__': main()
