"""Offline, append-only form learnset code generation."""
import json
from pathlib import Path
from dex_moves import MOVES
R=Path(__file__).resolve().parents[1]
data=json.loads((R/'data/forms/moves.json').read_text(encoding='utf8'))
ids={m[1]:i+1 for i,m in enumerate(MOVES) if m[1]}
out=['#pragma once','// Generated by tools/gen_form_moves.py; stable saved move IDs.','struct FormLearnRow { MoveId move; uint8_t level; };','struct FormLearnIndex { uint16_t dex,form,offset; uint8_t count; };','static const FormLearnRow FORM_LEARN_ROWS[] = {']
index=[];offset=0
for f in data['forms']:
    assert len(f['learnset'])<128
    index.append((f['dex'],f['form_id'],offset,len(f['learnset'])))
    for slug,level in f['learnset']:out.append(f'  {{{ids[slug]}, {level}}}, // {slug}')
    offset+=len(f['learnset'])
out+=['};','static const FormLearnIndex FORM_LEARN_INDEX[] = {']
out+=['  {'+', '.join(map(str,i))+'},' for i in index]
out+=['};','']
(R/'form_moves_data.h').write_text('\n'.join(out),encoding='utf8')
print(len(index),'form pools;',offset,'rows; existing 695 IDs unchanged')
