"""Official-site portraits and NPC-only stills -> compact flash art.

Copyright Pokemon/Nintendo/Creatures/Game Freak. NOT CC-licensed sprite art.
Sources and SHA256 are recorded separately. --fetch requires network; normal
regeneration is offline from the checked-in source images.
"""
from pathlib import Path
from urllib.request import Request, urlopen
from urllib.parse import urljoin
import argparse, hashlib, json, re
from PIL import Image, ImageOps
R=Path(__file__).resolve().parents[1]
D=R/'data/gyms/art'
p=argparse.ArgumentParser();p.add_argument('--fetch',action='store_true');p.add_argument('--check',action='store_true');a=p.parse_args()
assert not (a.check and a.fetch), 'check must be offline and read-only'
D.mkdir(parents=True,exist_ok=True)
def get(url):
    return urlopen(Request(url,headers={'User-Agent':'Mozilla/5.0'}),timeout=45).read()
entries=[]
sv={'KATY':'230112_01','BRASSIUS':'220907_02','IONO':'221014_01','KOFU':'230112_02','LARRY':'230112_03','RYME':'230112_05','TULIP':'230112_04','GRUSHA':'220803_05','GEETA':'220907_01'}
for key,ident in sv.items():
    entries.append(dict(key=key,size=32,url=f'https://www.pokemon.co.jp/ex/sv/assets/img/character/{ident}/thumbnail.jpg',page=f'https://www.pokemon.co.jp/ex/sv/ja/character/{ident}/'))
galar={'MILO':'grass-gym-leader-milo','NESSA':'water-gym-leader-nessa','KABU':'fire-gym-leader-kabu','BEA':'fighting-gym-leader-bea','ALLISTER':'ghost-type-gym-leader-allister','OPAL':'fairy-type-gym-leader-opal','GORDIE':'rock-type-gym-leader-gordie','MELONY':'ice-type-gym-leader-melony','PIERS':'dark-type-gym-leader-piers','RAIHAN':'dragon-type-gym-leader-raihan'}
old={e['key']:e for e in json.loads((D/'sources.json').read_text())} if (D/'sources.json').exists() else {}
for key,slug in galar.items():
    page=f'https://swordshield.pokemon.com/en-us/people-galar-region/{slug}/'
    if a.fetch:
        html=get(page).decode()
        urls=re.findall(r'<img[^>]+src="([^"]+)"',html)
        candidates=[x for x in urls if '/articles/' in x and key.lower() in x and 'hover' not in x]
        assert candidates,(key,urls)
        url=urljoin(page,candidates[0])
    else: url=old[key]['url']
    entries.append(dict(key=key,size=32,url=url,page=page))
for dex in (839,847,956,973):
    entries.append(dict(key=f'NPC_{dex}',size=64,url=f'https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/{dex}.png',page=f'https://www.pokemon.com/us/pokedex/{dex}'))
entries.append(dict(key='NPC_849_LOW',size=64,url='https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/849_f2.png',page='https://www.pokemon.com/us/pokedex/toxtricity'))
out=['#pragma once','// Generated by tools/gen_gym_art.py. Copyright holders: see CREDITS.md.','#include <stdint.h>','#include <string.h>','struct GymArt { const char *key; uint8_t size; const uint16_t *pal; const uint8_t *idx; };']
sheet=Image.new('RGB',(320,((len(entries)+4)//5)*100),'#f5eee5')
for n,e in enumerate(entries):
    src=D/(e['key']+'.img')
    if a.fetch and not src.exists():
        raw=get(e['url']); Image.open(__import__('io').BytesIO(raw)).verify();src.write_bytes(raw)
    raw=src.read_bytes();e['sha256']=hashlib.sha256(raw).hexdigest()
    if a.check: assert e['sha256']==old[e['key']]['sha256'],f'Changed source: {src}'
    im=Image.open(src).convert('RGBA');im=im.crop(im.getbbox())
    size=e['size']; im=ImageOps.contain(im,(size,size),Image.Resampling.LANCZOS)
    canvas=Image.new('RGBA',(size,size));canvas.alpha_composite(im,((size-im.width)//2,(size-im.height)//2))
    rgb=Image.new('RGB',(size,size),'#f5eee5');rgb.paste(canvas,mask=canvas.getchannel('A'))
    q=rgb.quantize(colors=31,method=Image.Quantize.MEDIANCUT);pal=q.getpalette();idx=list(q.getdata());alpha=list(canvas.getchannel('A').getdata())
    idx=[v if alpha[i]>=100 else 255 for i,v in enumerate(idx)]
    colors=[((pal[i]>>3)<<11)|((pal[i+1]>>2)<<5)|(pal[i+2]>>3) for i in range(0,93,3)]
    key=e['key'];out.append(f'static const uint16_t GA_{key}_PAL[] = {{'+','.join(map(str,colors))+'};')
    out.append(f'static const uint8_t GA_{key}_IDX[] = {{'+','.join(map(str,idx))+'};')
    sheet.paste(rgb.resize((64,64)),((n%5)*64,(n//5)*100))
    from PIL import ImageDraw
    ImageDraw.Draw(sheet).text(((n%5)*64,(n//5)*100+66),key,fill='black')
out.append('static const GymArt GYM_ART[] = {')
for e in entries:
    key=e['key'];out.append(f'{{"{key}",{e["size"]},GA_{key}_PAL,GA_{key}_IDX}},')
out+=['};','static inline const GymArt *gymArt(const char *key) { for (const auto &a : GYM_ART) if (!strcmp(key,a.key)) return &a; return nullptr; }','static inline bool gymNpcHasArt(int16_t dex) { return dex==839 || dex==847 || dex==956 || dex==973; }']
if a.check:
    assert (R/'gym_art.h').read_text(encoding='utf-8')=='\n'.join(out)+'\n','Stale gym art header'
    assert json.loads((D/'sources.json').read_text())==entries,'Stale source manifest'
else:
    (R/'gym_art.h').write_text('\n'.join(out)+'\n',encoding='utf-8')
    (D/'sources.json').write_text(json.dumps(entries,indent=2)+'\n',encoding='utf-8')
    (R/'build/gyms').mkdir(parents=True,exist_ok=True);sheet.save(R/'build/gyms/art-preview.png')
print('PASS:',len(entries),'official-site images; manifest + header generated')
